### ISSUE TITLE
Case browser 500 error for reporters with blank volume numbers

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1005]
E.g. https://cite.capapi.org/ga-app/

`django.urls.exceptions.NoReverseMatch: Reverse for 'volume' with keyword arguments '{'volume_number': '', 'series_slug': 'ga-app'}' not found. 1 pattern(s) tried: ['(?P<series_slug>[^/]+)\\/(?P<volume_number>[^/]+)\\/$']`

**Comment by bensteinberg** [comment]
Same for https://cite.capapi.org/mich-app/

**Comment by bensteinberg** [comment]
I thought this was going to be a simple fix to `cite/templates/cite/series.html`, but I can't see how to link to a volume with no volume number, even if we rewrite the displayed "number" to `None` or something; do we need a new route/view for volumes by volume ID?

**Comment by bensteinberg** [comment]
Maybe a data problem, not a display problem? The barcode for the Mich. App. volume with `volume_number = ''` is 32044054680277; the note field says "NOT ON FILE AT HD. KF 7.13.16"; I don't see that volume in captar or in the xfer/from_vendor bucket.

**Comment by bensteinberg** [comment]
The barcode for the Ga. App. volume with `volume_number = ''` is 32044057754251 and the scope reason is "No Cases" (both this and the Mich. App. volume have `out_of_scope = t`.

**Comment by bensteinberg** [comment]
```
capdb=> select barcode, out_of_scope from capdb_volumemetadata where volume_number = '';
    barcode     | out_of_scope 
----------------+--------------
 HNSRYH         | t
 32044057754251 | t
 32044097104137 | t
 HNSRYG         | t
 32044038597522 | t
 32044038594875 | t
 32044057619405 | t
 32044054421730 | t
 HNSRYK         | t
 32044054680277 | t
 HNSRYI         | t
 HNSRYJ         | t
 32044038595161 | t
 32044046858239 | t
 NOTALEPH001781 | t
(15 rows)
```

**Comment by bensteinberg** [comment]
(There are 600 volumes where `volume_number is null`; `out_of_scope` varies. I can paste them here if that'll help.)
