### ISSUE TITLE
Esc key to close settings only works when settings panel has focus

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#1033]
The feature "settings panels can be closed with escape key" from #1032 works, but only after   you've clicked in the settings.

**Comment by bensteinberg** [comment]
(Of course, this may be the desired behavior, in which case please close this issue.)

**Comment by jcushman** [comment]
Yes, I think this is working as intended. The panels now take focus automatically, so that might have been the missing piece.
