### ISSUE TITLE
opinions not properly nested

### ISSUE THREAD

**Issue by coopermayne** [harvard-lil/capstone#1044]
mixing multiple opinions together (which loses metadata about which part is concurrence, which is dissent etc)

example: https://api.case.law/v1/cases/5874681/?full_case=true&format=html

other cases with this issue from US reporter bulk collection attached as json file (there's like 500)
[errors.json.gz](https://github.com/harvard-lil/capstone/files/3288304/errors.json.gz)

**Comment by coopermayne** [comment]
[errors.json.gz](https://github.com/harvard-lil/capstone/files/3288324/errors.json.gz)

this is the full list from US reporter cases I'm working on

Best,

**Comment by kilbergr** [comment]
This seems like it was the result of an error during ingest, known limitation of dataset.

**Comment by kilbergr** [comment]
https://github.com/harvard-lil/capstone/issues/307

**Comment by cath9** [comment]
This work is not currently planned, so we are closing the issue.
