### ISSUE TITLE
Special handling for v. in case name search

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1079]
We might want to normalize ("lemmatize"?) some very common case name elements, so "US vs Howard" and "United States v. Howard" match the same case.

**Comment by mlissner** [comment]
We have a synonym list with about 450 entries. Here's `v.`: https://github.com/freelawproject/courtlistener-solr-server/blob/master/solr/cores/collection1/conf/lang/synonyms_en.txt#L445

And "United States", "US", "USA": https://github.com/freelawproject/courtlistener-solr-server/blob/master/solr/cores/collection1/conf/lang/synonyms_en.txt#L439

It could surely be improved, but it's a good start.

**Comment by kilbergr** [comment]
Not doing for CAP read only.
