### ISSUE TITLE
API should (probably?) Include the IDs along with the URLs in API results

### ISSUE THREAD

**Issue by mlissner** [harvard-lil/capstone#1083]
Another thing we ran into using Django rest framework. It's nice for humans to put URLs in the API responses, but it sucks for computers. For example, I want to normalize on your reporter IDs, but they are URLs in the API responses, instead of being IDs. Yeah, we can parse that, but, as our developer says, that's "annoying."

Our fix was to extend the `HyperlinkedModelSerializer` like so:

```
class HyperlinkedModelSerializerWithId(serializers.HyperlinkedModelSerializer):
    """Extend the HyperlinkedModelSerializer to add IDs as well for the best of
    both worlds.
    """
    id = serializers.ReadOnlyField()
```

Easy tweak and it adds the id field everywhere. We rolled this out as a minor point release to the API since it's fully backwards compatible (it only adds a field, doesn't mess with any existing ones).

**Comment by mlissner** [comment]
While we're making changes to the data formats, is now a good time to roll this out too? Should be a very easy change if you're set up like we are.

**Comment by ChefAndy** [comment]
I added IDs in a few places in #1083. If there's some spots where we need more ids, re-open this ticket or add a new one.
