### ISSUE TITLE
Update alert message on failed ngram search

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#1099]
I’m still getting the “fewer than 100” message sometimes on trends - like if I type in a gibberish word that presumably appears 0 times. Maybe just an update to the alert message?

e.g. https://case.law/trends/?q=weierd

**Comment by bensteinberg** [comment]
Fixed in https://github.com/harvard-lil/capstone/commit/90927476259fe84c440d4c61f2ffa34334e7114f but not yet deployed to prod.
