### ISSUE TITLE
Put xml declaration back in case xml

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1115]
As discussed in #1106, the `<?xml version='1.0' encoding='utf-8'?>` is currently missing from case xml served by the API. Edit render_case.py to put it back.

**Comment by jcushman** [comment]
We are currently hit or miss on whether `<?xml version='1.0' encoding='utf-8'?>` is included in case XML output -- it depends whether sync_case_body_cache has been run since this fix landed for a given case. We should make it consistent, maybe just by a big update query on capdb_casebodycache.xml.

**Comment by kilbergr** [comment]
Notes: All cases listed in these examples (https://api.case.law/v1/cases/435537/?full_case=true&body_format=xml, https://api.case.law/v1/cases/5493627/?full_case=true&body_format=xml, https://api.case.law/v1/cases/5493627/?full_case=true&body_format=xml) do now have the xml tag. 

The function being called in `sync_case_body_cache`, `render_xml`, has this line, which is what I think Jack was referencing above:

```
return "<?xml version='1.0' encoding='utf-8'?>\n{}".format(self.render_markup(case).replace('\xad', ''))
```

In the test/dev db:
Running `select id from capdb_casebodycache where xml not like '%<?xml version%';` yields nothing.
Running `select id from capdb_casebodycache where xml like '%\xad%';` yields 5 rows, but they all contain `<?xml version='1.0' encoding='utf-8'?>`. The `xad` inclusions appear to be flukes related to containing images (i.e. http://api.case.test:8000/v1/cases/4152409/?full_case=true&body_format=xml, http://api.case.test:8000/v1/cases/4152919/?full_case=true&body_format=xml). I'm going to try with a bulk download.

**Comment by kilbergr** [comment]
Using a bulk download from CO have identified the following 37 cases from 2020 (colo_xml_20200604.zip) without the `<?xml` tag:

```
{"id": 89218, "url": "https://api.capapi.org/v1/cases/89218/",
{"id": 89219, "url": "https://api.capapi.org/v1/cases/89219/",
{"id": 89220, "url": "https://api.capapi.org/v1/cases/89220/",
{"id": 89221, "url": "https://api.capapi.org/v1/cases/89221/",
{"id": 89222, "url": "https://api.capapi.org/v1/cases/89222/",
{"id": 89223, "url": "https://api.capapi.org/v1/cases/89223/",
{"id": 89224, "url": "https://api.capapi.org/v1/cases/89224/",
{"id": 89225, "url": "https://api.capapi.org/v1/cases/89225/",
{"id": 89226, "url": "https://api.capapi.org/v1/cases/89226/",
{"id": 89227, "url": "https://api.capapi.org/v1/cases/89227/",
{"id": 89228, "url": "https://api.capapi.org/v1/cases/89228/",
{"id": 89230, "url": "https://api.capapi.org/v1/cases/89230/",
{"id": 89233, "url": "https://api.capapi.org/v1/cases/89233/",
{"id": 89235, "url": "https://api.capapi.org/v1/cases/89235/",
{"id": 89237, "url": "https://api.capapi.org/v1/cases/89237/",
{"id": 89239, "url": "https://api.capapi.org/v1/cases/89239/",
{"id": 89241, "url": "https://api.capapi.org/v1/cases/89241/",
{"id": 89244, "url": "https://api.capapi.org/v1/cases/89244/",
{"id": 89246, "url": "https://api.capapi.org/v1/cases/89246/",
{"id": 89248, "url": "https://api.capapi.org/v1/cases/89248/",
{"id": 89249, "url": "https://api.capapi.org/v1/cases/89249/",
{"id": 89251, "url": "https://api.capapi.org/v1/cases/89251/",
{"id": 89252, "url": "https://api.capapi.org/v1/cases/89252/",
{"id": 89254, "url": "https://api.capapi.org/v1/cases/89254/",
{"id": 89255, "url": "https://api.capapi.org/v1/cases/89255/",
{"id": 89256, "url": "https://api.capapi.org/v1/cases/89256/",
{"id": 89258, "url": "https://api.capapi.org/v1/cases/89258/",
{"id": 89260, "url": "https://api.capapi.org/v1/cases/89260/",
{"id": 89261, "url": "https://api.capapi.org/v1/cases/89261/",
{"id": 89262, "url": "https://api.capapi.org/v1/cases/89262/",
{"id": 89263, "url": "https://api.capapi.org/v1/cases/89263/",
{"id": 89264, "url": "https://api.capapi.org/v1/cases/89264/",
{"id": 89265, "url": "https://api.capapi.org/v1/cases/89265/",
{"id": 89267, "url": "https://api.capapi.org/v1/cases/89267/",
{"id": 89268, "url": "https://api.capapi.org/v1/cases/89268/",
{"id": 89269, "url": "https://api.capapi.org/v1/cases/89269/",
{"id": 89270, "url": "https://api.capapi.org/v1/cases/89270/",
```

But if you start looking for the xml tag in the current db, it is present:

e.g. https://api.case.law/v1/cases/89218/?full_case=true&body_format=xml, https://api.case.law/v1/cases/89219/?full_case=true&body_format=xml,https://api.case.law/v1/cases/89262/?full_case=true&body_format=xml etc.

<img width="1064" alt="Screen Shot 2023-01-05 at 1 28 23 PM" src="https://user-images.githubusercontent.com/7401870/210853845-b0b667ad-76c8-48e6-b26b-c2047837f96b.png">

Indeed, if you bulk download from the more recent Sept 21 directory, you'll find the same case (89218) now has the appropriate tag.

I suspect this means that the current xml files have the correct tag, but if you bulk download from easier versions, some may lack the correct tag. I think updating the earlier version bulk files would change their status as earlier versions. I think this concern doesn't exist in the current file versions and therefore the issue can be closed.

**Comment by kilbergr** [comment]
Closing due to the above with Jack sign off [in Slack](https://hlslil.slack.com/archives/C0JS2FR3J/p1672944134597559?thread_ts=1672943921.409489&cid=C0JS2FR3J)
