### ISSUE TITLE
Documentation error - case endpoints

### ISSUE THREAD

**Issue by GPPassos** [harvard-lil/capstone#1140]
In https://case.law/api/#endpoints

it currently is
```
API Base

https://api.case.law/

This is the base endpoint of CAPAPI. It just lists all of the available endpoints.

Case Browse/Search Endpoint

https://api.case.law/
```

However for Case Browse/Search Endpoint it should be `https://api.case.law/v1/cases/`

**Comment by ChefAndy** [comment]
Thanks for filing an issue! I've just tacked the API docs edit onto another PR that modifies the docs, so it should go through when that ends up working its way through our test environment and getting deployed. I'll leave this issue open until it's merged.

**Comment by GPPassos** [comment]
Thanks!
