### ISSUE TITLE
Exclude cases from out_of_scope volumes

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1161]
We currently show 10376 cases from volumes that are marked out_of_scope. We should filter out those cases by marking them as duplicates.

List of volume barcodes affected: `['HL4EEK', '32044132266552', '32044132255233', '32044057896201', 'HL5NAP', '32044132266529', '32044097502694', '32044110671344', '32044132264730', '32044132255878', 'HL5EVH', '32044132255258', '32044109601872', '32044132255282', '32044132255852', 'NOTALEPH000733', 'HL4DQC', 'HL4CIU', 'HL4CGI', '32044061389664', 'HL5LE4', '32044132255894', '32044132254764', '32044132254772', '32044078504321', '32044057894636', '32044132255837', '32044132254442', '32044097503395', '32044047099643', '32044061988663', '32044132255829', '32044132264755', '32044132255266', '32044109601427', '32044132254582', '32044047100888', '32044132254467', '32044132255274', '32044061388708', '32044065991390', '32044065986135', '32044132255241', '32044132255902', 'HL5C7I', 'HL4C4I', 'HL4ED7', '32044132266511', '32044078593928', '32044132264748', 'HL58J8', '32044132255209', '32044078504172', '32044078618915', '32044061389318', '32044132266503', '32044132266537', '32044132255225', '32044132254798', '32044132255860', '32044132248394', '32044132254756', '32044078506607', '32044132266495', '32044132255845', '32044132255217', '32044132254749', '32044132254723', '32044059730051', '32044132266545', '32044132279241', '32044132254731', '32044132254459', '32044132255886', 'HL5KM6', 'NOTALEPH000734', '32044132254780', 'HL4BQC']`

**Comment by ChefAndy** [comment]
```
from capd.models import VolumeMetadata

set_dup_of_blank = ['HL4EEK', '32044132266552', '32044132255233', '32044057896201', 'HL5NAP', '32044132266529',
            '32044097502694', '32044110671344', '32044132264730', '32044132255878', 'HL5EVH', '32044132255258',
            '32044109601872', '32044132255282', '32044132255852', 'NOTALEPH000733', 'HL4DQC', 'HL4CIU', 'HL4CGI',
            '32044061389664', 'HL5LE4', '32044132255894', '32044132254764', '32044132254772', '32044078504321',
            '32044057894636', '32044132255837', '32044132254442', '32044097503395', '32044047099643', '32044061988663',
            '32044132255829', '32044132264755', '32044132255266', '32044109601427', '32044132254582', '32044047100888',
            '32044132254467', '32044132255274', '32044061388708', '32044065991390', '32044065986135', '32044132255241',
            '32044132255902', 'HL5C7I', 'HL4C4I', 'HL4ED7', '32044132266511', '32044078593928', '32044132264748',
            'HL58J8', '32044132255209', '32044078504172', '32044061389318', '32044132266503',
            '32044132266537', '32044132255225', '32044132254798', '32044132255860', '32044132248394', '32044132254756',
            '32044078506607', '32044132266495', '32044132255845', '32044132255217', '32044132254749', '32044132254723',
            '32044059730051', '32044132266545', '32044132254731', '32044132254459', '32044132255886',
            'HL5KM6', 'NOTALEPH000734', '32044132254780', 'HL4BQC']

with_dup_of = {'32044078618915': '32044078621703','32044132279241' : '32044106825532'}

for bc in set_dup_of_blank:
    vol = VolumeMetadata.objects.get(pk=bc)
    vol.set_duplicate(None)

for bc in with_dup_of:
    vol = VolumeMetadata.objects.get(pk=bc)
    vol.set_duplicate(with_dup_of[bc])
```

There were only a couple of barcodes on this list that had an obvious dup— a volume with the same reporter ID and volume number— which was in-scope. Do you think these instances need any other investigation @jcushman? If not, we can just go ahead and run this when our environment stabilizes.

**Comment by jcushman** [comment]
Thanks! I marked the duplicate volumes. The others are now filtered by checking `volume.out_of_scope` in `CaseMetadata.reindex_cases`.
