### ISSUE TITLE
Loading bulk data into local capstone?

### ISSUE THREAD

**Issue by GPPassos** [harvard-lil/capstone#1164]
Hi,

I was wondering if its supported to load bulk data into a local version of the capstone application (so that one could, for instance, use the same API but for data stored locally), or if it's only possible to load from the more specific XML files you have.

Thanks!

**Comment by ChefAndy** [comment]
Hello,
We don't currently support this, but we've had one other request for a more user-friendly (or, user-possible, rather) ingest process. We've recently changed up our internal storage/processing schema and it might be a good time to revisit the issue to see if it will fit on the roadmap. I think we should track this in the original issue, #657.
