### ISSUE TITLE
Update CaseMetadata.reporter to match CaseMetadata.volume.reporter

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1191]
Oops -- the nominative fix updated volumes' reporters, but not cases' reporters, which means that individual cases will still come back with their `"reporter":` showing the nominative volume, and the bulk export will spread out the cases among the nominatives. Should fix, and figure out what if anything to redo as far as export/index.

**Comment by kilbergr** [comment]
Not fixed after such a long time we consider it dead.
