### ISSUE TITLE
addslashes redirects in the API should include the CORS header

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1224]
Currently this url has a CORS header:

```
$ curl -i https://api.case.law/v1/cases/3299832/
...
Access-Control-Allow-Origin: *
```

But the redirect if you hit the same URL with no slash doesn't have a CORS header:

```
$ curl -i https://api.case.law/v1/cases/3299832
HTTP/1.1 301 Moved Permanently
...
Location: /v1/cases/3299832/
```

This creates a confusing situation if an API user tries to use a URL without an end slash -- hopefully fixed, or at least producing a more useful error, if we include `Access-Control-Allow-Origin: *` on addslashes redirects.

**Comment by bensteinberg** [comment]
Fixed in #1225.
