### ISSUE TITLE
fab task `add_test_case` appears to be broken

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#1232]
```botocore.exceptions.ClientError: An error occurred (InvalidObjectState) when calling the GetObject operation: The operation is not valid for the object's storage class```

**Comment by raolivei** [comment]
you can fix it by restoring your objects from Glacier back to S3

**Comment by docsuleman** [comment]
fab add_test_case has been removed despite its mention on the readme page. is there any other method using which I can add some test data? the capstone API database is completely empty.  what I want is actually to import my country case-law data. can someone guide me in the right direction so I can format my data accordingly and import it into the database?

**Comment by jcushman** [comment]
We now have test volumes stored at https://case.law/download/developer/volumes which can be loaded with `fab import_web_volumes`. These volumes consist of exported Django fixtures and PDFs; there isn't currently a good method for ingesting outside cases in a standard format.
