### ISSUE TITLE
Couple of PA reporters with no cases

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#1309]
https://cite.case.law/pittsb-lj/

https://cite.case.law/pa-lj-rep/

Generally, can we check any reporters that have no cases? We should not be exposing reporters that have no cases.

**Comment by jcushman** [comment]
These links still work but are no longer listed in the reporter options on beta, due to running `fab update_reporter_years`

**Comment by ChefAndy** [comment]
Added exclusion for reporters without start_year in the series view in PR #1324
