### ISSUE TITLE
Add <img> to casebody xml schema

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1314]
We've now added <img> tags to our XML output to match the HTML output -- should document in the casebody xml schema.

**Comment by ChefAndy** [comment]
@jcushman: Do we have an idea where images occur within a case? Just opinions? Also in headnotes, etc?

**Comment by kilbergr** [comment]
Schemas live in another repo. Find the link and pursue.

**Comment by jcushman** [comment]
https://github.com/harvard-lil/CaselawAccessProjectSchemas

**Comment by kilbergr** [comment]
@jcushman can you check I have perms to access this repo? I get 404 despite being signed in/in the LIL org.

**Comment by kilbergr** [comment]
https://github.com/harvard-lil/CaselawAccessProjectSchemas/pull/2

Explanation added to the above repo about why we care about keeping this up to date:

These schemas are linked as a reference in CAP's XML documents via the `<xmlns>` attribute. We intend to keep them up to date with our XML documents to avoid future confusion around XML formats for the document types within this repo.

An example: 
https://api.case.law/v1/cases/2747110/?full_case=true&body_format=xml
Contains 

```
"data": "<?xml version='1.0' encoding='utf-8'?>\n<casebody firstpage=\"1\" lastpage=\"5\" xmlns=\"[http://nrs.harvard.edu/urn-3:HLS.Libr.US_Case_Law.Schema.Case_Body:v1\](http://nrs.harvard.edu/urn-3:HLS.Libr.US_Case_Law.Schema.Case_Body:v1%5C)">\n
```

That url redirects to the schema, so we want the schema to look like the casebody doc.
