### ISSUE TITLE
Resolve d̶u̶p̶l̶i̶c̶a̶t̶e̶ ̶r̶e̶p̶o̶r̶t̶e̶r̶s̶ possibly duplicate volumes where the reporter_id and volume number are the same

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#1322]

**Comment by abziegler** [comment]
Andy working on detailed report to cover some of the complexity that has arisen on this

**Comment by ChefAndy** [comment]
I sent onedrive invites to @jcushman and @abziegler with the volume duplicate report in onedrive. The spreadsheet has the stats and I've got all the PDFs for the referenced volumes in the pdfs directory. I'm guessing this should be enough to figure out what action we should take with most of these volumes... we should discuss, maybe at dev meeting today, what the best way to move forward with this is.

**Comment by ChefAndy** [comment]
At @jcushman's request, added the headers to the otherwise completely inscrutable spreadsheet in onedrive.

**Comment by ChefAndy** [comment]
https://docs.google.com/document/d/1ZnscDdiumGpR2zlnxzKKisSVvCI3VctB6QYkavqIqsQ/edit

**Comment by jcushman** [comment]
Ran `fab run_script:scripts.duplicate_volume_reorg,dry_run=false`. Duplicate volumes appear to be resolved on beta! Output of the script attached.

[duplicate_volume_reorg.log](https://github.com/harvard-lil/capstone/files/4704149/duplicate_volume_reorg.log)
