### ISSUE TITLE
API URL when using filters

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#1340]
When you use filters to drill down on the API, the URL that results includes all parameters, whether used or not. Here's an example that used only two filters: `?search=antitrust&jurisdiction=us` but which yielded this URL:

https://api.case.law/v1/cases/?cite=&name_abbreviation=&jurisdiction=us&reporter=&decision_date_min=&decision_date_max=&docket_number=&court=&court_id=&search=antitrust&full_case=&body_format=text

This is an obnoxious URL. It's long and contains a bunch of unused information. Can we construct the URL with only the used filters? Should we?

**Comment by ChefAndy** [comment]
This would involve putting some javascript in the browsable API template to intercept the form submission and trim out blank fields. Personally, I think that this would be heavy handed for a cosmetic issue— it would introduce the possibility of bugs when submitting the form. Is there some functionality/UX/view that we can add to the purposefully cleaner-looking GUI search that would make that a first choice over the browsable API?

**Comment by abziegler** [comment]
I tend to think of this more as a usability issue than a cosmetic one. There's something hard-to-use about a filter form that produces an API call that no one would ever construct themselves. But if there's not a good way to ignore the blank form fields, it's probably not worth prioritizing.
