### ISSUE TITLE
Correct title of Puerto Rico Reports

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#1341]
https://api.case.law/v1/reporters/1077/

**Comment by ChefAndy** [comment]
<img width="589" alt="Screen Shot 2020-03-18 at 9 43 39 AM" src="https://user-images.githubusercontent.com/1882536/76966939-1960a480-68fd-11ea-9a17-61f33a1fa760.png">

<img width="535" alt="Screen Shot 2020-03-18 at 9 47 34 AM" src="https://user-images.githubusercontent.com/1882536/76967240-883dfd80-68fd-11ea-9b24-d01a355072e9.png">

These two shots are from the earliest and latest volumes, respectively, in this reporter series. I assume we should use the name, as printed. LMK if that's not correct.
