### ISSUE TITLE
Missing Jurisdiction

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#1348]
In 140 cases, all of which have `in_scope` is set to false, no jurisdiction is specified.

All of these have `duplicative` set to false, which might also be something. One case is missing a court.

| Cite | ID | Reporter | Jurisdiction | Court | Volume Barcode |
| ---- | --- | -------- | ------------ | ----- | -------------- |
| Norton v. Stevens, 18 F. Cas. 430, 1 Hayw. & H. 94 (1842) | 12117830 | F. Cas. | No Jurisdiction | D.C Orphans' Ct. | NOTALEPH001458 |
| Baldwin v. Easterling, 754 P.2d 942 (1988) | 12120188 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| In re Disciplinary Action of Davis, 754 P.2d 63 (1988) | 12117857 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| Matthew v. Cook, 754 P.2d 666 (1988) | 12119621 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| Cox Corp. v. Vertin, 754 P.2d 938 (1988) | 12120169 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| In re Criminal Investigation, 7th District Court No. CS-1, 754 P.2d 633 (1988) | 12119615 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| Rothey v. Walker Bank & Trust Co., 754 P.2d 1222 (1988) | 12120429 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| Williams v. Public Service Commission, 754 P.2d 41 (1988) | 12117834 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| Forbes v. St. Mark's Hospital, 754 P.2d 933 (1988) | 12120147 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| DeBry v. Occidental/Nebraska Federal Savings Bank, 754 P.2d 60 (1988) | 12117849 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| Mountain States Telephone & Telegraph Co. v. Public Service Commission, 754 P.2d 928 (1988) | 12120141 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| State v. Bell, 754 P.2d 55 (1988) | 12117841 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| State v. Auble, 754 P.2d 935 (1988) | 12120159 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| Fashion Place Associates v. Glad Rags, Inc., 754 P.2d 940 (1988) | 12120180 | P.2d | No Jurisdiction | Utah | 32044061438586 |
| Wolf v. District of Columbia, 609 A.2d 672 (1992) | 12119150 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Mitchell v. United States, 609 A.2d 1099 (1992) | 12119926 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Gooch v. United States, 609 A.2d 259 (1992) | 12117833 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Friend v. Friend, 609 A.2d 1137 (1992) | 12119986 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Portillo v. United States, 609 A.2d 687 (1992) | 12119190 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Cormier v. McRae, 609 A.2d 676 (1992) | 12119167 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Johnson v. States, 609 A.2d 1112 (1992) | 12119934 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| In re Muckelroy, 609 A.2d 265 (1992) | 12117846 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Edmonds v. United States, 609 A.2d 1131 (1992) | 12119954 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Moore v. United States, 609 A.2d 1133 (1992) | 12119978 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Beckham v. United States, 609 A.2d 1122 (1992) | 12119942 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| In re Arceneaux, 609 A.2d 280 (1992) | 12117854 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Brewer v. United States, 609 A.2d 1140 (1992) | 12119995 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Gray v. Citizens Bank of Washington, 609 A.2d 1143 (1992) | 12120000 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| In re Herndon, 609 A.2d 682 (1992) | 12119175 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Abolaji v. District of Columbia Taxicab Commission, 609 A.2d 671 (1992) | 12119139 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Herskovitz v. Garmong, 609 A.2d 1128 (1992) | 12119948 | A.2d | No Jurisdiction | D.C. | 32044057699829 |
| Hill v. District of Columbia Department of Employment Services, 717 A.2d 909 (1998) | 12119916 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Bragdon v. United States, 717 A.2d 878 (1998) | 12119893 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Brooks v. United States, 717 A.2d 323 (1998) | 12117883 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Karriem v. District of Columbia, 717 A.2d 317 (1998) | 12117871 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Long v. District of Columbia Department of Employment Services, 717 A.2d 329 (1998) | 12117894 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| D'Ambrosio v. Colonnade Council of Unit Owners, 717 A.2d 356 (1998) | 12117950 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| District of Columbia v. Jerry M., 717 A.2d 866 (1998) | 12119880 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Jackson v. District of Columbia Police & Firefighters Retirement & Relief Board, 717 A.2d 904 (1998) | 12119911 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| In re Day, 717 A.2d 883 (1998) | 12119898 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| McCracken v. Walls-Kaufman, 717 A.2d 346 (1998) | 12117938 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Wright v. United States, 717 A.2d 304 (1998) | 12117835 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Brown v. Consolidated Rail Corp., 717 A.2d 309 (1998) | 12117842 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Scolaro v. District of Columbia Board of Elections & Ethics, 717 A.2d 891 (1998) | 12119907 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| United Mine Workers v. Moore, 717 A.2d 332 (1998) | 12117908 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| In re Willingham, 717 A.2d 342 (1998) | 12117924 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Anderson v. George, 717 A.2d 876 (1998) | 12119885 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| In re Kiely, 717 A.2d 913 (1998) | 12119921 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| In re Estate of Spinner, 717 A.2d 362 (1998) | 12117970 | A.2d | No Jurisdiction | D.C. | 32044053192779 |
| Tasters Ltd. v. Department of Employment Security, 819 P.2d 361 (1991) | 12117843 | P.2d | No Jurisdiction | Utah Ct. App. | 32044061439238 |
| State v. Singh, 819 P.2d 356 (1991) | 12117831 | P.2d | No Jurisdiction | Utah Ct. App. | 32044061439238 |
| State v. Sawyers, 819 P.2d 806 (1991) | 12119288 | P.2d | No Jurisdiction | Utah Ct. App. | 32044061439238 |
| Josupeet v. City of Niagara Falls, 70 Misc. 638 (1911) | 1855168 | Misc. | No Jurisdiction | N.Y. Sup. Ct. | 32044078475118 |
| Southern Trucking Service, Inc. v. Mississippi Sand & Gravel, Inc., 483 So. 2d 321 (1986) | 12117912 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Messer v. State, 483 So. 2d 338 (1986) | 12117983 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Nelson v. State, 483 So. 2d 1364 (1986) | 12121115 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Watson v. State, 483 So. 2d 1358 (1986) | 12121058 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Rose v. Mercury Marine, 483 So. 2d 1351 (1986) | 12121038 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Frost v. State, 483 So. 2d 1345 (1986) | 12121036 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Thompson v. State, 483 So. 2d 690 (1986) | 12119944 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Ingram v. State, 483 So. 2d 688 (1986) | 12119938 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Miller v. Miller, 483 So. 2d 1362 (1986) | 12121104 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Hemmingway v. State, 483 So. 2d 1335 (1986) | 12121029 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Wyman v. Anthony, 483 So. 2d 1361 (1986) | 12121082 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Graham v. State, 483 So. 2d 381 (1986) | 12118173 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Odom v. State, 483 So. 2d 343 (1986) | 12118013 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Watson v. State, 483 So. 2d 1326 (1986) | 12121023 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Shaw v. Ten Point Co., 483 So. 2d 325 (1986) | 12117928 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Mississippi State Highway Commission v. Harreld, 483 So. 2d 693 (1986) | 12119959 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Richardson v. Shoffner, 483 So. 2d 1326 (1986) | 12121020 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Ratliff v. City of Jackson, 483 So. 2d 325 (1986) | 12117921 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Mid-South Packers, Inc. v. Vance, 483 So. 2d 1359 (1986) | 12121063 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Haralson v. Haralson, 483 So. 2d 378 (1986) | 12118120 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Smith v. Massey Ferguson Credit Corp., 483 So. 2d 1334 (1986) | 12121028 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Porter v. Porter, 483 So. 2d 1359 (1986) | 12121068 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Garrott v. City of Ocean Springs, 483 So. 2d 1362 (1986) | 12121094 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Wash v. State, 483 So. 2d 1361 (1986) | 12121089 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Alford v. City of Pascagoula, 483 So. 2d 1362 (1986) | 12121099 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Livingston v. State, 483 So. 2d 1360 (1986) | 12121069 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Noxubee County Board of Education v. Overton, 483 So. 2d 301 (1985) | 12117872 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Ethridge v. Ethridge, 483 So. 2d 370 (1986) | 12118090 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Ward v. State, 483 So. 2d 1362 (1986) | 12121091 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Garvis v. State, 483 So. 2d 312 (1986) | 12117895 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Hanner v. State, 483 So. 2d 1358 (1986) | 12121054 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Anderson v. State, 483 So. 2d 1360 (1986) | 12121072 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Brabham v. Brabham, 483 So. 2d 341 (1986) | 12117997 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Sutherland-El v. State, 483 So. 2d 254 (1986) | 12117827 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Smith v. Cleveland Truck & Tractor Repair, Inc., 483 So. 2d 254 (1985) | 12117838 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| First Southern Savings Ass'n v. Singing River Mall Co., 483 So. 2d 1359 (1986) | 12121060 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Watson v. State, 483 So. 2d 1357 (1986) | 12121050 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Jenkins v. State, 483 So. 2d 1330 (1986) | 12121026 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Jackson v. State, 483 So. 2d 1353 (1986) | 12121040 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Spain v. Holland, 483 So. 2d 318 (1986) | 12117904 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Wilson v. Wilson, 483 So. 2d 1361 (1986) | 12121085 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Deposit Guaranty National Bank v. Roberts, 483 So. 2d 348 (1986) | 12118043 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Pool v. State, 483 So. 2d 331 (1986) | 12117971 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Creel v. Watson, 483 So. 2d 1357 (1986) | 12121045 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Holmes v. State, 483 So. 2d 684 (1986) | 12119932 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Payne v. Mississippi Employment Security Commission, 483 So. 2d 1360 (1986) | 12121081 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Powell v. State, 483 So. 2d 363 (1986) | 12118077 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Satcher v. Wiser, 483 So. 2d 694 (1986) | 12119966 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Smith v. Estate of Wactor, 483 So. 2d 684 (1986) | 12119925 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Brown v. State, 483 So. 2d 328 (1986) | 12117951 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Dufour v. State, 483 So. 2d 307 (1985) | 12117886 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Cook v. State, 483 So. 2d 371 (1986) | 12118105 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Shelton v. Puckett, 483 So. 2d 354 (1986) | 12118051 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Fairley v. State, 483 So. 2d 345 (1986) | 12118031 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Coleman v. State, 483 So. 2d 680 (1986) | 12119920 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| McGhee v. Mississippi Employee Appeals Board, 483 So. 2d 381 (1986) | 12118152 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Brock v. State, 483 So. 2d 358 (1986) | 12118059 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Barrett v. Ballard, 483 So. 2d 304 (1985) | 12117880 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Cavanah v. State, 483 So. 2d 693 (1986) | 12119950 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Evans v. State, 483 So. 2d 1363 (1986) | 12121106 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Foster v. Barefoot, 483 So. 2d 1358 (1986) | 12121051 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Bankers Life & Casualty Co. v. Crenshaw, 483 So. 2d 254 (1985) | 12117864 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Metcalf v. Coca-Cola Bottling Works, Inc., 483 So. 2d 1363 (1986) | 12121112 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Waites v. State, 483 So. 2d 381 (1986) | 12118192 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Wilson v. Service Broadcasters, Inc., 483 So. 2d 1339 (1986) | 12121034 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Pittman v. Mississippi Employment Security Commission, 483 So. 2d 1363 (1986) | 12121109 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Myers v. State, 483 So. 2d 382 (1986) | 12118220 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Burleson v. Burleson, 483 So. 2d 1357 (1986) | 12121042 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Sisson v. State, 483 So. 2d 1338 (1986) | 12121031 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Smith v. Everett, 483 So. 2d 325 (1986) | 12117941 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Butler v. State, 483 So. 2d 1360 (1986) | 12121076 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Black v. Black, 483 So. 2d 380 (1986) | 12118135 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Reves v. State, 483 So. 2d 381 (1986) | 12118213 | So.2d | No Jurisdiction | Miss. | 32044109655340 |
| Office of Disciplinary Counsel v. Perkel, 47 Pa. D. & C. 5th 401 (2015) | 12187837 | Pa. D. & C. 5th | No Jurisdiction | No Court | 32044142582097 |
| Roberts v. City of Madison, 250 Wis. 317 (1947) | 12117832 | Wis. | No Jurisdiction | Wis. | 32044078614955 |
| Navarra v. Navarra, 46 Pa. D. & C. 5th 51 (2015) | 12186387 | Pa. D. & C. 5th | No Jurisdiction | Lawrence Cty. Ct. C.P. | 32044133503201 |
| Williams v. United States, 240 A.2d 131 (1968) | 12117836 | A.2d | No Jurisdiction | D.C. | 32044109580274 |
| Martin v. Martin, 240 A.2d 363 (1968) | 12119007 | A.2d | No Jurisdiction | D.C. | 32044109580274 |
| Solway Decorating Co. v. Merando, Inc., 240 A.2d 361 (1968) | 12118992 | A.2d | No Jurisdiction | D.C. | 32044109580274 |
| Cohen v. Cohen, 240 A.2d 662 (1968) | 12119789 | A.2d | No Jurisdiction | D.C. | 32044109580274 |
| Parks v. Ratcliff, 240 A.2d 659 (1968) | 12119782 | A.2d | No Jurisdiction | D.C. | 32044109580274 |
| Bailey v. Washington Motor Truck Transportation Employees Pension Trust, 240 A.2d 133 (1968) | 12117839 | A.2d | No Jurisdiction | D.C. | 32044109580274 |
| Watkins v. United States, 240 A.2d 656 (1968) | 12119774 | A.2d | No Jurisdiction | D.C. | 32044109580274 |
| Toliver v. Durham, 240 A.2d 359 (1968) | 12118983 | A.2d | No Jurisdiction | D.C. | 32044109580274 |
| Nichols v. Pitman, 4 Colo. L. Rep. 841 (1884) | 12145963 | Colo. L. Rep. | No Jurisdiction | High Ct. J. Ch. | NOTALEPH001838 |
| Hughes v. Percival, 4 Colo. L. Rep. 221 (1883) | 12131320 | Colo. L. Rep. | No Jurisdiction | House of Lords | NOTALEPH001838 |

**Comment by ChefAndy** [comment]
Figured this might be more useful in a spreadsheet.

[missing_jurisdiction.xlsx](https://github.com/harvard-lil/capstone/files/4192115/missing_jurisdiction.xlsx)

**Comment by jcushman** [comment]
> all of which have in_scope is set to false

That's just because they have no jurisdiction -- in_scope is defined as "has a jurisdiction and court, and isn't `duplicative` or `duplicate`".

Looks like it would make sense to spot check a case or two from each court to make sure nothing weird is going on, and set the jurisdiction for each of these to the jurisdiction for that court. The "House of Lords" one might be a special case though ...

**Comment by jcushman** [comment]
You know what else would help is to add the jurisdiction from initial_metadata for each of these. Like for one of the first ones: 

```
>>> CaseMetadata.objects.get(id=12120188).initial_metadata.metadata['court']['jurisdiction']
'utah'
```

Looks like the issue was just a typo lowercase 'u' in the xml jurisdiction. Adding that column might show what's going on with most of these.

**Comment by abziegler** [comment]
@abziegler needs to go through spreadsheet and identify jurisdiictions for cases without them - see Slack message 2:24 on 3/11

**Comment by abziegler** [comment]
@ChefAndy will review Innodata jurisdiction data and see if that gives us wha twe're missing

**Comment by ChefAndy** [comment]
[missing_jurisdiction_updated.xlsx](https://github.com/harvard-lil/capstone/files/4345404/missing_jurisdiction_updated.xlsx)

**Comment by ChefAndy** [comment]
Added the values from the initial_metadata. Looks like there are a couple "United Kingdom" jurisdiction values, one is entirely missing, one is /40. Most will be an easy, straight substitution. Going to add another column with suggested replacement for the easier ones.

**Comment by ChefAndy** [comment]
Google sheet with updated suggested values, minus the two UK values:

https://docs.google.com/spreadsheets/d/1qGiVoM04huhPWc5IwqrIq0Bd9juZ-WneqGGtjyBIP94/edit#gid=0

**Comment by ChefAndy** [comment]
Resolved for all Jurisdictions except the U.K.

Need to create a U.K. jurisdiction and update the cases.

**Comment by ChefAndy** [comment]
Done. Also update the court for one PA case as detailed in issue #1431
