### ISSUE TITLE
Sharing preview for case quotation urls

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1356]
When you share a link to a quotation, like https://cite.case.law/f/84/158/6725108/?highlight=This+article+%E2%80%94+crocus%E2%80%94is+found+to+be%2C+and+in+fact+is%2C+a+color , it should have an image preview that includes the highlighted text.

This can now be done pretty simply using the same technique as for Trends image previews.

**Comment by kilbergr** [comment]
Not doing for CAP read only.
