### ISSUE TITLE
Incorrect redirect on login from API

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#1363]
When logging in from https://api.case.law/v1/ the user is redirected to a 404, https://case.law/v1/

**Comment by bensteinberg** [comment]
Even though the value of `next` looks right, this now redirects to the front page.

**Comment by anastasia** [comment]
aha. I believe this is because we have this setting in `settings_base.py`: `LOGIN_REDIRECT_URL = '/'`. I think it's overriding absolute_uri

**Comment by bensteinberg** [comment]
But this works for e.g. the about page -- just not for the subdomain?

**Comment by bensteinberg** [comment]
Like `allowed_hosts` is not being set for this redirect.
