### ISSUE TITLE
text selection for PDFs is broken in Firefox viewer

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#1382]
In the Firefox PDF viewer, selecting text misses some words and all spaces. Chrome and Safari appear to be fine. Selecting works fine in Preview when you download the file. Oddly, I can't get About Firefox to show me what version I'm running, but will add it here when I find out.

**Comment by bensteinberg** [comment]
Firefox is up-to-date, version 73.0.1.

**Comment by jcushman** [comment]
It might be helpful to find a scanned PDF with OCRed text that we didn't create, and see if that one works differently in Firefox -- I'm not clear if this is something we did wrong, or just that Firefox isn't applying the smoothing it should to OCRed PDFs.
