### ISSUE TITLE
Firefox only prints first page of cases on cite.case.law

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1398]

**Comment by lkfitz** [comment]
Replicated in Firefox; bug inactive in Chrome and Safari.

**Comment by anastasia** [comment]
this is actually the case with all of our pages with the same layout. This might be related but it's also a very old issue that has supposedly been fixed on Firefox: https://stackoverflow.com/questions/4609007/firefox-printing-only-1st-page
