### ISSUE TITLE
PDF URL with semicolon redirects indefinitely

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#1415]
The PDF linked at https://cite.case.law/ala-app/43/258/ is unreachable. I believe it's because we don't handle the semi-colon in [get_pdf_url](https://github.com/harvard-lil/capstone/blob/ffa47360ebc75bcc370461a0fa634eb45e241d00/capstone/capdb/models.py#L976-L978), so `request.build_absolute_uri()` never matches `pdf_url` at [line 144 of cite/views.py](https://github.com/harvard-lil/capstone/blob/19296518b8af305dcb5cec1c671acc1dda791c15/capstone/cite/views.py#L144).

**Comment by ChefAndy** [comment]
Seems to be resolved. PDF link works fine as tested in Chromium and FF.
