### ISSUE TITLE
Case browser selection menu can itself be selected

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#1425]
<img width="811" alt="Screen Shot 2020-03-31 at 3 57 15 PM" src="https://user-images.githubusercontent.com/1494102/78074411-b34e3580-7370-11ea-8e9a-4e87e6ffd066.png">

**Comment by jcushman** [comment]
I updated the title of this -- I don't think it's specific to elide/redact, but just that the menu sometimes inserts itself inside the selection as you drag. For example, I just got the menu text included on my clipboard when I did a regular drag and command-c.

Can think of a couple options:

* Hide the menu on mouse down, and don't show it until mouse up.
* Make the menu text non-selectable with CSS.
