### ISSUE TITLE
API not returning cases queried by name when name has an apostrophe

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#1441]
For example, these queries fail when `/cases/?name_abbreviation=[casename]`:

- Wilson's Admr. v. Hines - https://api.case.law/v1/cases/?name_abbreviation=Wilson%E2%80%99s%20Admr.%20v.%20Hines

- Lewis v. Young Men's Christian Association - https://api.case.law/v1/cases/?name_abbreviation=Lewis%20v.%20Young%20Men%E2%80%99s%20Christian%20Ass%27n

**Comment by ChefAndy** [comment]
Sometimes it works.
https://api.case.law/v1/cases/?name_abbreviation=Thomas%E2%80%99+Lessee+v.+Godfrey

In this case, the apostrophe is at the end of the word. I suspect the tokenizer is to blame here— investigating.

**Comment by ChefAndy** [comment]
Whatever this is, it's not being broken by our implementation of CaseFilterBackend.get_filter_query_params. Even using the default implementation of that script with lower-casing does the same thing.
