### ISSUE TITLE
For Libraries

### ISSUE THREAD

**Issue by lkfitz** [harvard-lil/capstone#1487]
This page shares how libraries are connecting with the Caselaw Access Project.

Location: Standalone page that will be (for now) added to the gallery as a new module.

Note: Markdown file attachments not accepted; page content in markdown shown below.

----

title: For Libraries

How are libraries connecting with the Caselaw Access Project? 

Libraries use home-grown guides to share resources with their communities. The Caselaw Access Project is shown in 50+ library guides. Here are a dozen examples!

1. [APIs for Scholarly Resources](https://libraries.mit.edu/scholarly/publishing/apis-for-scholarly-resources/), Massachusetts Institute of Technology (MIT).
2. [Open Access](https://libguides.asu.edu/openaccess/opendata-science), Arizona State University.
3. [Finding Humanities Data](https://guides.lib.utexas.edu/c.php?g=815698&p=5821508), University of Texas Libraries.
4. [Primary Sources: A Research Guide](https://umb.libguides.com/PrimarySources/openaccess), University of Massachusetts Boston.
5. [Law and Legal Studies](https://guides.library.umass.edu/legal/statecases), University of Massachusetts Amherst.
6. [Data and Statistics](https://guides.lib.virginia.edu/c.php?g=515084&p=5578061), University of Virginia.
7. [Text Mining](https://libguides.umn.edu/text-mining), University of Minnesota.
8. [Legal Resources on the Web, Law in Other Jurisdictions](https://libportal.nus.edu.sg/frontend/ms/c-j-koh-law-library/research/legal-resources-on-the-web/law-in-other-jurisdictions), National University of Singapore.
9. [Law School Affordable Course Materials](https://lawguides.bc.edu/affordablecoursematerials/subjectmatter), Boston College Law Library.
10. [Sources of Legal and Judicial Data](https://libguides.princeton.edu/c.php?g=916665&p=6607543), Princeton University. 
11. [How to Find Free Case Law Online](http://guides.loc.gov/free-case-law/caselaw-access-project), Library of Congress.
12. [Legal History](https://guides.library.brandeis.edu/c.php?g=633861&p=4432485), Brandeis University.

How can you support the Caselaw Access Project at your library? Share our data with your community, and [continue the push](https://case.law/action/) for digital-first case publishing.

How are you using the Caselaw Access Project at your library? From our library to yours, [we’re excited to hear from you](https://case.law/contact/).

**Comment by ChefAndy** [comment]
https://case.law/docs/user_pathways/libraries
