### ISSUE TITLE
Case ID 12415118 missing opinion tag

### ISSUE THREAD

**Issue by garetht** [harvard-lil/capstone#1501]
Justice Sotomayor's concurrence in the `casebody.data` field of case ID 12415118 is incorrectly tagged as a `p` instead of an `<opinion type="concurrrence">`

```
<p id=\"b968-14\">Justice SOTOMAYOR, with whom Justice KENNEDY, Justice THOMAS, and Justice GORSUCH join, concurring.</p>
```

**Comment by cath9** [comment]
This work is not currently planned, so we are closing the issue.
