### ISSUE TITLE
Correct multiline quotes in early SCOTUS cases

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1528]
In early scotus cases like this (at least) multiline quotes were presented with a quote mark at the start of each line:

http://cite.case.test:8000/us/5/45/

![image](https://user-images.githubusercontent.com/376272/88196440-30970200-cc0f-11ea-89b7-75c41d528401.png)

Some are blockquotes but some are just quotes that wrap a line or two. This messes up the text:

`The caveat of Wilson v. Mason originated in the supreme court for the district of Kentucky in 1785, while Kentucky was a part of the commonwealth of Virginia, and the record states, “ that heretofore, viz. at a supreme “ court for the district of Kentucky, held at Danville in the “ said district, in the month of March, 1785, came George “ Wilson and caused a certain caveat to be entered against “ George Mason, which is in the following words, viz. “ Let no grant issue to George Mason, of Fairfax coun- “ ty, for 8,300 acres of land, in Jefferson county, sur- `

It would be great to find and fix these automatically, since they're laborious to do by hand.

**Comment by ChefAndy** [comment]
Might be worth addressing at the same time as #395
