### ISSUE TITLE
Add mechanism for do-not-edit warnings

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#1545]
In our new deployment, we will sometimes clone the data to perform long-running migrations, then swap the running data for the cloned and migrated data. During this procedure, we don't want admin users to make edits that will be blasted when the swap happens. Maybe add something to various templates to warn users not to edit, when a flag file is present? Or even suppress the editing functions altogether? Probably the former will be easier/more flexible.

**Comment by kilbergr** [comment]
Not doing for CAP read only.
