### ISSUE TITLE
Elasticsearch error when highlighting large text field

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1558]
```Internal Server Error: /v1/cases/

RequestError at /v1/cases/
RequestError(400, 'search_phase_execution_exception', 'The length of [casebody_data.text.opinions.text] field of [4320337] doc of [cases] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!')

Request Method: GET
Request URL: https://api.case.law/v1/cases/?search=2019+views+from+the+bench&page_size=5&court=8th-cir-bankr-app-panel&court=bap-8th-cir-1&court=1st-cir-bankr-app-panel&court=9th-cir-bankr-app-panel&court=bap-9th-cir-1&court=2nd-cir-bankr-app-panel&court=6th-cir-bankr-app-panel&court=10th-cir-bankr-app-panel&court=bap-8th-cir&court=bap-1st-cir&court=9th-cir-4&court=bap-9th-cir-2&court=bap-9th-cir&court=bap-2d-cir&court=bap-6th-cir&court=bap-10th-cir&court=bankr-cd-cal&court=bankr-cd-ill&court=bankr-d-alaska&court=bankr-d-ariz&court=bankr-d-colo&court=bankr-d-colo-2&court=bankr-ddc&court=bankr-dc&court=bankr-d-conn&court=bankr-d-del&court=bankr-d-fla&court=bankr-d-guam&court=bankr-d-haw&court=d-idaho-2&court=bankr-d-idaho&court=bankr-d-iowa&court=bankr-d-kan&court=bankr-d-me&court=bankr-d-md&court=bankr-d-mass&court=bankr-d-minn&court=bankr-d-mont&court=bankr-d-neb&court=bankr-d-nev&court=bankr-dnh&court=bankr-dnj&court=bankr-dnm&court=bankr-dnd&court=bankr-d-or&court=bankr-dpr&court=bankr-pr&court=bankr-dri&court=bankr-dsc&court=bankr-dsd&court=bankr-d-tenn&court=bankr-tenn&court=bankr-d-tennessee&court=bankr-dvi&court=bankr-d-utah&court=bankr-d-vt&court=bankr-d-wyo&court=bankr-ed-ark&court=bankr-ed-cal&court=bankr-ed-ky&court=bankr-md-la-1&court=bankr-ed-la&court=bankr-ed-mass&court=bankr-ed-mich&court=bankr-ed-mo&court=bankr-edny&court=bankr-ednc&court=bankr-ed-okla&court=bankr-ed-pa&court=bankr-ed-tex-1&court=bankr-ed-tenn&court=bankr-ed-tex&court=bankr-ed-va&court=bankr-ed-wash&court=bank-ed-wis&court=bankr-ed-wis&court=bankr-md-ala&court=bankr-md-fla&court=bankr-md-ga&court=bankr-md-la&court=bankr-mdnc&court=bankr-mdnc-1&court=bankr-md-pa&court=bankr-md-tenn&court=bankr-nd-ala-1&court=bankr-nd-ala&court=bankr-d-colo-1&court=bankr-nd-cal&court=bankr-nd-fla&court=bankr-nd-ga&court=bankr-nd-ill&court=bankr-nd-ind-1&court=bankr-nd-ind&court=bankr-nd-iowa&court=bankr-nd-miss&court=bankr-ndny-1&court=bankr-ndny&court=bankr-nd-ohio&court=bankr-nd-okla&court=bankr-nd-tex&court=bankr-nd-w-va&court=bankr-sd-fla-1&court=bankr-sd-ala&court=bankr-sd-cal&court=bankr-sd-fla&court=bankr-sd-fla-2&court=bankr-sd-flo&court=bankr-sd-ga&court=bankr-sd-ill&court=bankr-sd-ind&court=bankr-sd-iowa&court=bankr-sd-miss&court=bankr-sdny&court=bankr-sd-ohio&court=bankr-sd-fla-3&court=bankr-sd-tex&court=bankr-sd-w-va&court=bankr-wd-ark&court=bankr-wd-ark-1&court=bankr-wd-ky&court=bankr-wd-la&court=bankr-wd-mich&court=bankr-wd-mo&court=bankr-wd-mo-1&court=bankr-wdny-2&court=bankr-wdny&court=bankr-wdnc&court=bankr-wd-okla&court=bap-1st-cir-1&court=bankr-wd-pa&court=bankr-wd-tenn&court=bankr-wd-tex&court=bankr-wd-va&court=bankr-wd-wash-2&court=bankr-wd-wash&court=bankr-wd-wis&court=bank-wd-wis&court=bankr-wdny-1&ordering=-decision_date
Django Version: 2.2.13
Python Executable: /usr/bin/uwsgi-core
Python Version: 3.7.3
Server time: Wed, 12 Aug 2020 17:47:37 +0000```

**Comment by bensteinberg** [comment]
```curl -X PUT "http://localhost:9200/cases/_settings" -H 'Content-Type: application/json' -d '{ "index": { "highlight.max_analyzed_offset": 10000000 } }'```
is a temporary fix.

**Comment by bensteinberg** [comment]
This appears to be unset under some circumstances: find out what they are.

**Comment by ChefAndy** [comment]
This search works for me:

`https://api.case.law/v1/cases/?search=2019+views+from+the+bench&page_size=5&court=8th-cir-bankr-app-panel&court=bap-8th-cir-1&court=1st-cir-bankr-app-panel&court=9th-cir-bankr-app-panel&court=bap-9th-cir-1&court=2nd-cir-bankr-app-panel&court=6th-cir-bankr-app-panel&court=10th-cir-bankr-app-panel&court=bap-8th-cir&court=bap-1st-cir&court=9th-cir-4&court=bap-9th-cir-2&court=bap-9th-cir&court=bap-2d-cir&court=bap-6th-cir&court=bap-10th-cir&court=bankr-cd-cal&court=bankr-cd-ill&court=bankr-d-alaska&court=bankr-d-ariz&court=bankr-d-colo&court=bankr-d-colo-2&court=bankr-ddc&court=bankr-dc&court=bankr-d-conn&court=bankr-d-del&court=bankr-d-fla&court=bankr-d-guam&court=bankr-d-haw&court=d-idaho-2&court=bankr-d-idaho&court=bankr-d-iowa&court=bankr-d-kan&court=bankr-d-me&court=bankr-d-md&court=bankr-d-mass&court=bankr-d-minn&court=bankr-d-mont&court=bankr-d-neb&court=bankr-d-nev&court=bankr-dnh&court=bankr-dnj&court=bankr-dnm&court=bankr-dnd&court=bankr-d-or&court=bankr-dpr&court=bankr-pr&court=bankr-dri&court=bankr-dsc&court=bankr-dsd&court=bankr-d-tenn&court=bankr-tenn&court=bankr-d-tennessee&court=bankr-dvi&court=bankr-d-utah&court=bankr-d-vt&court=bankr-d-wyo&court=bankr-ed-ark&court=bankr-ed-cal&court=bankr-ed-ky&court=bankr-md-la-1&court=bankr-ed-la&court=bankr-ed-mass&court=bankr-ed-mich&court=bankr-ed-mo&court=bankr-edny&court=bankr-ednc&court=bankr-ed-okla&court=bankr-ed-pa&court=bankr-ed-tex-1&court=bankr-ed-tenn&court=bankr-ed-tex&court=bankr-ed-va&court=bankr-ed-wash&court=bank-ed-wis&court=bankr-ed-wis&court=bankr-md-ala&court=bankr-md-fla&court=bankr-md-ga&court=bankr-md-la&court=bankr-mdnc&court=bankr-mdnc-1&court=bankr-md-pa&court=bankr-md-tenn&court=bankr-nd-ala-1&court=bankr-nd-ala&court=bankr-d-colo-1&court=bankr-nd-cal&court=bankr-nd-fla&court=bankr-nd-ga&court=bankr-nd-ill&court=bankr-nd-ind-1&court=bankr-nd-ind&court=bankr-nd-iowa&court=bankr-nd-miss&court=bankr-ndny-1&court=bankr-ndny&court=bankr-nd-ohio&court=bankr-nd-okla&court=bankr-nd-tex&court=bankr-nd-w-va&court=bankr-sd-fla-1&court=bankr-sd-ala&court=bankr-sd-cal&court=bankr-sd-fla&court=bankr-sd-fla-2&court=bankr-sd-flo&court=bankr-sd-ga&court=bankr-sd-ill&court=bankr-sd-ind&court=bankr-sd-iowa&court=bankr-sd-miss&court=bankr-sdny&court=bankr-sd-ohio&court=bankr-sd-fla-3&court=bankr-sd-tex&court=bankr-sd-w-va&court=bankr-wd-ark&court=bankr-wd-ark-1&court=bankr-wd-ky&court=bankr-wd-la&court=bankr-wd-mich&court=bankr-wd-mo&court=bankr-wd-mo-1&&court=bankr-wdnc&court=bankr-wd-okla&court=bap-1st-cir-1&court=bankr-wd-pa&court=bankr-wd-tenn&court=bankr-wd-tex&court=bankr-wd-va&court=bankr-wd-wash-2&court=bankr-wd-wash&court=bankr-wd-wis&court=bank-wd-wis&ordering=-decision_date`

is this still a problem?
