### ISSUE TITLE
Alabama reporter has term dates instead of decision dates

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1598]
The Alabama reporter did not include case publication dates until volume 144. Prior to that volume, our decision_date field represents the court term the case was decided in (such as "[Dec. 1886](https://cite.case.law/ala/81/577/)"), rather than the date the decision was published. One exception is volume 132, which does include decision dates.

The Southern reporter has publication dates for the same cases, so these could be corrected later with access to that metadata.

Other reporters may have the same issue. Here's the sql query for fetching unique dates per volume for a reporter to review whether it likely has the issue: `select volume_number, ARRAY_AGG(DISTINCT decision_date_original) from capdb_casemetadata c, capdb_volumemetadata v where c.volume_id=v.barcode and c.reporter_id=296 group by v.volume_number order by volume_number;`

**Comment by ChefAndy** [comment]
Maybe worth checking CourtListener/Fastcase also?
