### ISSUE TITLE
Search: add explainers in download box

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#1666]
- if user is logged in (but isn't researcher), requesting full cases over their daily limit, add a warning?
- if user isn't logged in and requesting full cases, show warning
- to see next 10k cases, try sorting your results by date (dependent on #1665)

**Comment by anastasia** [comment]
Logged out user: “Full case text will be included only for <unrestricted cases>. If you <log in>, full text will be included for up to 500 cases per day.”

Logged in user without researcher access: “Full case text for <restricted cases> will be included for up to 500 cases per day. If you need to download full text for more cases, you might qualify for <scholarly research status>.”

**Comment by kilbergr** [comment]
Not doing for CAP read only.
