### ISSUE TITLE
Search: add pointer-events none to labels

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1672]
I think the `<label>` elements in this form want `pointer-events: none;` in their css:

![image](https://user-images.githubusercontent.com/376272/104194086-dd984d80-53ee-11eb-84e9-9fd373852f20.png)

In Firefox, clicking a label selects all the text in the input field. So if you're clicking to try to move the pointer within the input field, and you click the part of the input box showing the label, you select-all instead and end up deleting the text when you start typing.

**Comment by ChefAndy** [comment]
This was added at some point.
