### ISSUE TITLE
Standardize straight and curly quotes in case text

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1687]
We have cases where the OCR randomly brought in straight and curly quotes, like a quote starts with straight quotes and ends with curly quotes, which looks bad.

Can we smarten all the straight quotes? Or should we straighten all the curly quotes, and then attempt to smarten them again during rendering? Depends on how good that algorithm is I guess ...

**Comment by abziegler** [comment]
e.g. https://cite.case.law/ny2d/68/136/

![image](https://user-images.githubusercontent.com/2140548/105753823-474c4780-5f17-11eb-8567-2fb0cf72a235.png)

**Comment by ChefAndy** [comment]
Smart quote flakiness I've seen in word processors makes me think this is more challenging than it seems, but my gut says complete sentences and already-balanced quotes should make our problem much more straightforward than theirs. We could probably test our logic by looking for processed paragraphs in which the number of open quote marks doesn't match the number of close quote marks. Legitimate apostrophes, prime marks, image noise being OCR'd as single quotes, etc., will probably make double-quotes easier to tackle than single quotes. Though I imagine some double quotes were OCR'd as single quotes, which could gum things up... we won't know how much until we try, I guess. I think a first pass just for double quotes, at some point, is the way to go?
