### ISSUE TITLE
Handle frontend_url collision for nominative reporter

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1700]
"Rob." is both an official reporter and a nominative reporter, which is making it impossible to actually click through to the cases on this page:

https://cite.case.law/rob/1/

Should make `update_frontend_urls` smarter somehow (not sure if there's an efficient way to detect this edge case), and also give the citation disambiguation page a better fallback -- just link directly to the ID url instead of using the frontend_url field.

**Comment by kilbergr** [comment]
Fixed! Yay.
