### ISSUE TITLE
Handle format-neutral citation URLs

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1702]
For a case like 150 N.M. 1, 256 P.3d 13, 2011-NMSC-028, we should be able to look it up from the url /nmsc/2011/028/. This probably means special handling for the reporters with custom cite_formats in reporters-db.

**Comment by jcushman** [comment]
Once this is done we can also stop setting `disambiguate = True` in `get_frontend_url`:

```
        if not m:
            # if cite doesn't match the expected format, always disambiguate so URL resolution doesn't depend on cite value
            disambiguate = True
            # try to match "(year)-(series)-(case index)", e.g. "2017-Ohio-5699" and "2015-NMCA-053"
            m = re.match(r'(\S+)-(.+?)-(\S+)$', cite.cite)
```

**Comment by kilbergr** [comment]
Not doing for CAP read only.
