### ISSUE TITLE
Wrong reporter for (possibly duplicate) case 943185

### ISSUE THREAD

**Issue by charlesduan** [harvard-lil/capstone#1704]
The reporter for Central Virginia Community College v. Katz, [number 943185](https://api.case.law/v1/cases/943185/), is listed as West's Bankruptcy Reporter, though it should be West's Supreme Court Reporter. That said, the case is a duplicate of [number 5917860](https://api.case.law/v1/cases/5917860/); I'm not sure if that's considered a data error. If it is, then Otis v. McDonald, [number 12455289](https://api.case.law/v1/cases/12455289/), is a duplicate of [number 3644508](https://api.case.law/v1/cases/3644508/).

**Comment by cath9** [comment]
This work is not currently planned, so we are closing the issue.
