### ISSUE TITLE
capapi.org url in Illinois (more? all?) bulk results

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#1719]
`{"id": 182674, "url": "https://api.case.law/v1/cases/182674/", "name": "CATHY BEVIS et al., Petitioners, v. THE POLLUTION CONTROL BOARD et al., Respondents", "name_abbreviation": "Bevis v. Pollution Control Board", "decision_date": `[...]

**Comment by ChefAndy** [comment]
Still true. Not sure why I put the wrong data above. 

```{"id": 5497483, "url": "https://api.capapi.org/v1/cases/5497483/", "name": "Rudolph Lederer, appellee, v. Albert Sabath and Morris Sabath, appellants", "name_abbreviation": "Lederer v. Sabath", "decision_date": "1923-10-02", "docket_number": "Gen. No. 28,394", "first_page": "603", "last_page": "603", "citations": [{"cite": "231 Ill. App. 603", "type": "official"}], "volume": {"volume_number": "231", "barcode": "32044078690542", "url": "https://api.capapi.org/v1/volumes/32044078690542/"}, "reporter": {"id": 315, "full_name": "Illinois Appellate Court Reports", "url": "https://api.capapi.org/v1/reporters/315/"}, "court": {"name_abbreviation": "Ill. App. Ct.", "name": "Illinois Appellate Court", "id": 8837, "slug": "ill-app-ct", "url": "https://api.capapi.org/v1/courts/ill-app-ct/"}, "jurisdiction": {"name": "Ill.", "id": 29, "slug": "ill", "name_long": "Illinois", "url": "https://api.capapi.org/v1/jurisdictions/ill/", "whitelisted": true}, "cites_to": [], "frontend_url": "https://cite.capapi.org/ill-app/231/603/5497483/", "preview": [], "casebody": {"status": "ok", "data": {"judges": [], "attorneys": ["Sabath & Sabath, for appellants. Frederick W. Moore, for appellee."], "head_matter": "Rudolph Lederer, appellee, v. Albert Sabath and Morris Sabath, appellants.\nGen. No. 28,394.\nJudgment on note for plaintiff. Appeal from the Municipal Court of Chicago; the Hon. Samuel H. Trude, Judge, presiding. Heard in the second division of this court for the first district at the March term, 1923.\nAffirmed.\nOpinion filed October 2, 1923.\nSabath & Sabath, for appellants. Frederick W. Moore, for appellee.", "corrections": "", "opinions": [{"text": "Mr. Justice Fitch\ndelivered the opinion of the court.", "author": "Mr. Justice Fitch", "type": "majority"}], "parties": ["Rudolph Lederer, appellee, v. Albert Sabath and Morris Sabath, appellants."]}}}```

**Comment by kilbergr** [comment]
Sometimes the bulk data exports we do for other groups are done on the beta rather than primary server. If that's done wrong, it can end up with the capapi server. We have made changes that made this harder to do incorrectly. Check the Sept 2021 to see whether the issue still exists. If so, explore further. If not, close.

**Comment by kilbergr** [comment]
This is the same data as the above from the 9/21/21 export, which we confirm has the correct URL:

```
{"id": 5497483, "url": "https://api.case.law/v1/cases/5497483/", "name": "Rudolph Lederer, appellee, v. Albert Sabath and Morris Sabath, appellants", "name_abbreviation": "Lederer v. Sabath", "decision_date": "1923-10-02", "docket_number": "Gen. No. 28,394", "first_page": "603", "last_page": "603", "citations": [{"type": "official", "cite": "231 Ill. App. 603"}], "volume": {"url": "https://api.case.law/v1/volumes/32044078690542/", "volume_number": "231", "barcode": "32044078690542"}, "reporter": {"url": "https://api.case.law/v1/reporters/315/", "full_name": "Illinois Appellate Court Reports", "id": 315}, "court": {"url": "https://api.case.law/v1/courts/ill-app-ct/", "name_abbreviation": "Ill. App. Ct.", "slug": "ill-app-ct", "id": 8837, "name": "Illinois Appellate Court"}, "jurisdiction": {"id": 29, "name_long": "Illinois", "url": "https://api.case.law/v1/jurisdictions/ill/", "slug": "ill", "whitelisted": true, "name": "Ill."}, "cites_to": [], "frontend_url": "https://cite.case.law/ill-app/231/603/5497483/", "frontend_pdf_url": "https://cite.case.law/pdf/5497483/Lederer%20v.%20Sabath,%20231%20Ill.%20App.%20603%20(1923).pdf", "preview": [], "analysis": {"cardinality": 53, "char_count": 465, "ocr_confidence": 0.499, "sha256": "e05f7c8901d3214d86c3febee8dcd360749f54eb85fdb660e0e3db6e9f48a9fb", "simhash": "1:944e769cf4864c7a", "word_count": 73, "random_id": 465903331, "random_bucket": 7907}, "last_updated": "2021-08-10T21:31:29.927871+00:00", "provenance": {"date_added": "2019-08-29", "source": "CAP", "batch": "2018"}, "casebody": {"status": "ok", "data": {"judges": [], "parties": ["Rudolph Lederer, appellee, v. Albert Sabath and Morris Sabath, appellants."], "opinions": [{"text": "Mr. Justice Fitch\ndelivered the opinion of the court.", "type": "majority", "author": "Mr. Justice Fitch"}], "attorneys": ["Sabath & Sabath, for appellants. Frederick W. Moore, for appellee."], "corrections": "", "head_matter": "Rudolph Lederer, appellee, v. Albert Sabath and Morris Sabath, appellants.\nGen. No. 28,394.\nJudgment on note for plaintiff. Appeal from the Municipal Court of Chicago; the Hon. Samuel H. Trude, Judge, presiding. Heard in the second division of this court for the first district at the March term, 1923.\nAffirmed.\nOpinion filed October 2, 1923.\nSabath & Sabath, for appellants. Frederick W. Moore, for appellee."}}}
```

Can close :)
