### ISSUE TITLE
Add API field to search by opinion author

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1728]
We currently index opinion author, but don't expose it as a search field in the API:

```
casebody_data = fields.ObjectField(properties={
        'text': fields.ObjectField(properties={
            'opinions': fields.ObjectField(multi=True, properties={
                'author': fields.KeywordField(),
```

That field can technically be searched via the `search=` parameter with a search like `search=casebody_data.text.opinions.author:"Justice Scalia,"`, but that's gross -- you have to use a long weird prefix, and because it's a keyword field you need an exact text match. I think we want to change it to be a full-text field, and add a custom API param for it. It might also be nice if we can support fuzzy matching to deal with OCR errors.

**Comment by kilbergr** [comment]
Not doing for CAP read only.
