### ISSUE TITLE
Parse all cites with eyecite

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1752]
Eyecite should be able to parse each of our case citations as a single cite, something like this:

```
from eyecite import get_citations

for cite in Citation.objects.all():
    assert cite.cite == get_citations(cite.cite)[0].matched_text()
```

Failures could be either a mistake in eyecite or a mistake in our cites, but either way worth trying.

**Comment by kilbergr** [comment]
Not doing for CAP read only.
