### ISSUE TITLE
Some disambiguation pages only link to disambiguation pages.

### ISSUE THREAD

**Issue by raindrum** [harvard-lil/capstone#1791]
Example: _Wal-Mart Stores, Inc. v. Dukes_, [564 U.S. 338](https://cite.case.law/us/564/338/). Clicking this link leads to a disambiguation page with the following links:

- [Wal-Mart Stores, Inc. v. Dukes, 564 U.S. 338, 131 S. Ct. 2541, 180 L. Ed. 2d 374 (2011)](https://cite.case.law/us/564/338/)
- [Wal-Mart Stores, Inc. v. Dukes, 180 L. Ed. 2d 374, 2011 U.S. LEXIS 4567, 131 S. Ct. 2541, 564 U.S. 338 (2011)](https://cite.case.law/l-ed-2d/180/374/)

Both links lead to effectively the same disambiguation page; there appears to be no way to read the actual case.

The same error exists in the first 29 cases in [volume 564 of the U.S. Reporter](https://cite.case.law/us/564/), whose links all show a L. Ed. citation as well. Later links on the reporter page only show a U.S. Reporter citation, and they work correctly (with no disambiguation page).

**Comment by jcushman** [comment]
Hi! Thanks for this report. We tweaked this so you can click each link from the disambiguation page. There's still an underlying issue that causes these cases to have ambiguous `frontend_url` values in the API, but this is a start -- we'll track remaining progress over in #1700.
