### ISSUE TITLE
Missing case data; actual case text is being incorrectly redacted as if it is headnote text

### ISSUE THREAD

**Issue by jon-freed** [harvard-lil/capstone#1842]
A lot of case text in the Ohio St. (n.s.), Ohio St. 2d, and Ohio St. 3d series volumes has been incorrectly redacted.

For an example, see 125 Ohio St.3d 1438.  There should be text there about how the _Pahoundis v. Beamer_  case was not accepted for review. But the text has been redacted.  (It's visible through Google Scholar at https://scholar.google.com/scholar_case?case=14108544801672974801.)

I'm trying to trace docket numbers to reported cases, but I've run into a brick wall with the case.law data because of this issue.

I saw on your website that the "vendor redacted any headnotes", so this may not be a case.law issue per se.

**Comment by jcushman** [comment]
Hi, @jon-freed! Thanks for this report. To confirm, it looks like CAP doesn't have data from the "Appeals Not Accepted for Review" subsection of the "Orders Announced" appendix to Ohio case reporters. Sorry about that!

I'm not sure if there was an official policy during digitization about which procedural orders were included or not from appendices. Maybe @abziegler knows?

**Comment by cath9** [comment]
This work is not currently planned, so we are closing the issue.
