### ISSUE TITLE
Statute template - stray asterisk

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#1874]
Our single case template has a single asterisk/divider that looks especially lonely with statute pages

![image](https://user-images.githubusercontent.com/2140548/120717927-6d21c400-c496-11eb-8359-7b9e4e0d692c.png)

https://cite.case.law/citations/?q=48%20U.S.C.%20%C2%A7%20495

**Comment by kilbergr** [comment]
Not doing for CAP read only.
