### ISSUE TITLE
Chronolawgic: Missing elipsis in some cases?

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#1890]

**Comment by anastasia** [comment]
<img width="398" alt="Screen Shot 2021-06-16 at 9 02 10 PM" src="https://user-images.githubusercontent.com/1494102/122315382-ed5d1600-cee7-11eb-93f1-532d6e4c914e.png">
saw this just now, which seems different from the error we were seeing. Seems like a slightly bigger issue

**Comment by ChefAndy** [comment]
I'll take a look at this tomorrow. I think I messed this up.

**Comment by kilbergr** [comment]
If CourtListener wants to take Chronolawgic on, we should alert to this issue.
