### ISSUE TITLE
Chronolawgic: deleting event causes big big error 

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#1901]
We should probably be hiding the big scary errors, too. Highlighting to show error
This is a two issue issue:
<img width="1440" alt="Screen Shot 2021-06-16 at 9 16 43 PM" src="https://user-images.githubusercontent.com/1494102/122315494-31e8b180-cee8-11eb-80c6-46634e4d7561.png">

- hide big error
- stop error from happening

**Comment by ChefAndy** [comment]
I can't reproduce this. Can you get me a JSON dump of your timeline? This looks like it was trying to remove a whole bunch of events at the same time and I suspect it might be a data format issue.

**Comment by ChefAndy** [comment]
fixed w/back-end api update
