### ISSUE TITLE
Time/Date Representation

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#1903]
<img width="254" alt="Screen Shot 2021-06-17 at 12 00 14 AM" src="https://user-images.githubusercontent.com/1882536/122329214-01f8d880-ceff-11eb-9218-49b8fbc98c11.png">

The way we display dates is not ideal. 

- It's not precise enough to display one day events
- It makes less precise events seem like they started on a specific day
- We don't have a way to input less granular start dates and end dates
- There's no way to express events with nebulous start and end dates 
- The year label being in the middle of the year is confusing

**Comment by kilbergr** [comment]
Not doing for CAP read only.
