### ISSUE TITLE
Building Labs

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#2005]

**Comment by ChefAndy** [comment]
Questions:
- [ ] Who is going to use this?
- [ ] What do we want to say about ourselves by having this here?
- [ ] How visible should it be?
- [ ] How closely should it be aligned with the rest of the site?

Design ToDo:
- [ ] Write Copy
- [ ] Design Navigation Structure
- [ ] Design Nav Bar

Dev ToDo:
- [ ] Build Nav Bar
- [ ] Build Navigation Structure

**Comment by kilbergr** [comment]
Not doing for CAP read only.
