### ISSUE TITLE
subsequent 10,000 case batch link for big exports

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#2007]
In the export interface— in which the 10k case ES limit applies— we should have links to download the subsequent chunks.

**Comment by kilbergr** [comment]
Search page, when you click a CSV it sends an API request from your browser, so the JS has no way of knowing the cursor for the next 10k. The server generated it, but it has to be stored somewhere else for it to be accessed. JS and Django work. Then you could get more than 10k cases at a time.
