### ISSUE TITLE
How should we expose contrib data?

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#2008]
We should have an intuitive, organized way to expose contrib data wherever it makes sense to expose it.

**Comment by kilbergr** [comment]
Should FLP add this? If they did API V4, might be a home for this.
If you're a researcher and you generate metadata, you could upload to case.law's API and people could query against it. You could do that cleanly via adding a contrib dir to the API. They could use whatever taxonomy they defined in their namespace.
