### ISSUE TITLE
Elasticsearch Container Heap Size

### ISSUE THREAD

**Issue by 4ndygu** [harvard-lil/capstone#2031]
https://github.com/harvard-lil/capstone/blob/57647481de99bbe4af52b6dd5ade1954fba41a2d/capstone/docker-compose.yml#L16

Isn't 1Gb the default? https://www.elastic.co/guide/en/elasticsearch/reference/6.8/heap-size.html#heap-size. I would imagine we would want to cut this a little bit to reduce the potential of code 137 exits on the container. I hit this issue when setting up my deploy, and accordingly decreased the heap limits to 750m.

**Comment by jcushman** [comment]
Looking at git history, it looks like this was initially `512m` when we were on ES6. @ChefAndy then bumped it to 1024m, and then we moved to ES7, which has some dynamic default I don't understand: https://www.elastic.co/guide/en/elasticsearch/reference/7.16/important-settings.html#heap-size-settings

So I think you could either try dialing it back again, and see what works comfortably on ES7 with the number of documents you get from `fab import_web_volumes`, or try deleting it and see if the default behavior on ES7 is better.

**Comment by 4ndygu** [comment]
Thanks! Looks like I kept it at 750 and worked comfortably. But will leave this like so.
