### ISSUE TITLE
Allow restricted users to download entire volume PDFs

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#2039]
Some users with restricted accounts would like to download entire volume PDFs. We currently limit volume PDF links to unrestricted accounts, to avoid accounting for all of the cases in the volume. We could instead warn the user that downloading the volume will use such-and-such number of cases from their 500 cases per day, and then allow them to proceed.

**Comment by kilbergr** [comment]
Not doing for CAP read only.
