### ISSUE TITLE
Headmatter footnote not actually a footnote to headmatter

### ISSUE THREAD

**Issue by holtchesley** [harvard-lil/capstone#2049]
https://cite.case.law/ny2d/87/727/#b795-6 has a footnote that is incorrectly marked as a headmaster footnote in the raw data. 

How should we add something to the processing pipeline to catch these? 
Some idea:
 - Flag footnote marks without a corresponding footer entry.
 - Flag footnotes that appear before their mark.
 - Flag footnote/footer mismatched counts.

**Comment by jcushman** [comment]
This is a nice clean example where the footnote mark `1` appears in a different opinion section than the footnote text labeled `1`, and the footnote text just wants to move to follow the footnote mark. I don't think I'd edit cases where the marks and text fail to line up, but in a case where we can just move a footnote to make things line up correctly we should.
