### ISSUE TITLE
"Bad Request" Error Code 400

### ISSUE THREAD

**Issue by Heidolon** [harvard-lil/capstone#2054]
Under "Authentication" header, the "Access Limits" link (below) redirects you to error code 400

(https://case.law/docs/site_features/%7B%%20docs_url%20%22access_limits%22%20%7D)

**Comment by rebeccacremona** [comment]
Ooh, good stuff: this is a typo (a missing "%") in this file: https://github.com/harvard-lil/capstone/blob/develop/capstone/capweb/templates/docs/02_site_features/03_api.md
