### ISSUE TITLE
Dev setup needs tweaking

### ISSUE THREAD

**Issue by bensteinberg** [harvard-lil/capstone#2072]
In the instructions, this sequence is not correct:
```
fab init_dev_db
fab ingest_fixtures
fab import_web_volumes
fab refresh_case_body_cache
fab rebuild_search_index
```
Specifically, `fab rebuild_search_index` fails with 
```
  File "/app/capapi/documents.py", line 209, in prepare_casebody_data
    cites_by_id = {k: list(v) for k,v in groupby(sorted(outbound_cites, key=lambda c: c.opinion_id), lambda c: c.opinion_id)}
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```
This sequence works:
```
fab init_dev_db
fab ingest_fixtures
fab import_web_volumes
fab rebuild_search_index  # this fails fast!
fab refresh_case_body_cache
fab rebuild_search_index
```
but the first index rebuild fails.

**Comment by bensteinberg** [comment]
That is, https://github.com/harvard-lil/capstone/commit/473f4efc3b7cfae1f84ecf5f44f0c56f5e444a26 was not correct.

**Comment by bensteinberg** [comment]
@jcushman does it make sense that dropping and recreating the index in the first (failing) `fab rebuild_search_index` is necessary?

**Comment by lizadaly** [comment]
"Helpfully", this didn't happen to me and stepping through the original order worked fine.

```
root@4e0ab80e23c8:/app# fab rebuild_search_index
Really delete and recreate cases? [y/N] y
Deleting cases
Creating cases
Scheduling tasks to reindex volumes

Done.
```

**Comment by matteocargnelutti** [comment]
Mystery solved this week: It was likely Docker running out of resources.
I added a note to `README.md` with recommended settings.
