### ISSUE TITLE
On 'courts' filter, Supreme Court shows up as 'U.S.: U.S.' (as opposed to 'SCOTUS', 'U.S.: S.C.', e.g.) making it hard to search for/find

### ISSUE THREAD

**Issue by varun-magesh** [harvard-lil/capstone#2088]
Minor pet peeve of mine, I can maybe fix this if I have bit of spare time (won't let me assign since I don't have access to repo)!

**Comment by cath9** [comment]
This work is not currently planned, so we are closing the issue.
