### ISSUE TITLE
Some volumes of the US reporter are access restricted

### ISSUE THREAD

**Issue by PlatosTwin** [harvard-lil/capstone#2207]
@bensteinberg, great to see the CAP data open sourced!

As I was downloading volumes of the US reporter, I noticed that a number of them appear to be access restricted, presumably by mistake. E.g., `https://static.case.law/us/493.zip` takes you to the screenshot attached here.

So far, I've noticed similar behavior for volumes 498, 502, 506, 510, 513, 516, 519. The last four numbers follow a suspiciously regular pattern. [Edit: can confirm that this patter continues for at least several more iterations.]

<img width="1228" alt="Screenshot 2024-03-05 at 12 35 26 AM" src="https://github.com/harvard-lil/capstone/assets/59905317/3729a04b-07c0-40e5-836b-78d737fe2569">

**Comment by bensteinberg** [comment]
Thanks, I've begun to take a look. [493](https://static.case.law/us/493.zip) and [498](https://static.case.law/us/498.zip) download for me OK, but I got a 404 for [502](https://static.case.law/us/502.zip), which in fact appears not to be present. I'll see if there are any uploads still in progress, and will check the others.

**Comment by PlatosTwin** [comment]
Yep, seeing the same thing. My latest list is that the following give 404s: 502, 510, 513, 516, 519, 522, 525, 528, 531, 534, 537, 540, 543, 546, 562, 565, 568, 571.

Thanks!

**Comment by bensteinberg** [comment]
We're uploading the remainder now, which includes these and ~150 other volumes. I'll report here when we're done.

**Comment by bensteinberg** [comment]
The zip uploads were done yesterday, and we uploaded some corrected JSON files today. I'll close this ticket, but feel free to reopen it or file a new one if you notice any other problems.
