### ISSUE TITLE
Add file hashes to bulk-access page

### ISSUE THREAD

**Issue by stites** [harvard-lil/capstone#305]
For both security and verification of large downloads, it would be nice to have file hashes for all zip files located at https://capapi.org/bulk-access . If you wanted to be super-fancy, it would be nice to include a certified Harvard-LIL PGP key, similar to [they way debian serves their hashes](https://capapi.org/bulk-access/) -- I'll let the more security-minded folks push for that feature, though.

**Comment by ChefAndy** [comment]
Thanks again, @stites. We'll talk about it at our next meeting.

**Comment by ChefAndy** [comment]
Hashes included in bag-it data.
