### ISSUE TITLE
Improperly marked opinions

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#307]
Jason Todd: "I've been rooting around in the U.S. Reports, vols. 352--478, and I can add to your errata. There are well over a hundred separate opinions that I could find because they sport <author> tags, but which do not include their own <opinion> tags. In other words, multiple separate opinions are found within one set of <opinion>...</opinion> tags. It's each enough to identify them by counting, and easy enough to insert </opinion> <opinion>, but it's onerous to sort out the <footnote>s so that they are nested within the correct <opinion>s. If it would help, I could provide a list of filenames, but it would include some false positives (files where the <author>/<opinion> counts do not match, but for other reasons)."

**Comment by ChefAndy** [comment]
I perused some cases in this range and didn't see anything amiss. If someone has time to investigate and at least come up with a representative example, that could be useful.

**Comment by kilbergr** [comment]
https://github.com/harvard-lil/capstone/issues/1044
