### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#351]

**Comment by rebeccacremona** [comment]
I did a medium-thorough round of auditing last week, sending PRs where I could, making Github issues for anything that affected the design or was more complex than I felt like I could tackle in the moment.

I should probably do a second round in a few months, once things have settled down a bit. 

Want to tentatively schedule another round for right after Christmas?

**Comment by ChefAndy** [comment]
Yes!! And thank you SO MUCH FOR YOUR HELP!!!!!

**Comment by rebeccacremona** [comment]
Totally! Delighted to chip in!
