### ISSUE TITLE
Create new website

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#379]
- [x] loose mockups demonstrating flow 

- [x] designs in sketch

- [x] html/css/js for new site 

- [x] headline sizes
- [x] hamburger menu / navigation
- [x] footer styling
- [x] styling of “about” section, numbers on small screens
- [x] figure out sassevaluation errors

- [x] divide up sections for people to write about 
- [x] styling for phone !!!!
- [x] header sizes (phone)
- [x] navigation styles (phone)
- [x] column sizes (phone)

- [x] api documentation should be in /api
- [x] api should look better
- [x] log in /register/etc etc pages
- [x] don’t move around any models yet, just figure out scss?
- [x] bulk data download page / section

- [ ] https://accessibility.18f.gov
- [ ] add skip links

- [x] CHECK IN MOST POPULAR BROWSERS!
- [x] check phone sizes

**Comment by ChefAndy** [comment]
- I'll work on the API docs and Bulk Data Docs first
- Then make sure the tools page has stuff
- then that you can navigate to the API is navigable
- then API styling

**Comment by anastasia** [comment]
for reference

![desktop-11](https://user-images.githubusercontent.com/1494102/44751434-30a32b80-aae6-11e8-8bda-535b34461482.png)

![pixel-1](https://user-images.githubusercontent.com/1494102/44751504-5d574300-aae6-11e8-8013-f4998d5d65c3.png)

![desktop-12](https://user-images.githubusercontent.com/1494102/44751480-54ff0800-aae6-11e8-8942-89659f2c198b.png)

**Comment by anastasia** [comment]
x small screen user details
x fix footer on small screens
x fix footer in tools page
- tab navigation on small screens in nav menu is super weird
- figure out if you need to import _.scss files or without _
x fix branding white bar on chrome mobile (branding disappears)
x fix nav styles on mobile, homepage
x fix small numbers on index page
x gallery page (make working wordclouds and limericks)
x contact us form
- add links from states in map to capapi?jurisdiction=state_name
- figure out aria labels and sr-only
x fix gallery for small screens
x contact page for small screens
x footer should not have log in link if already logged in
x fix tests
x add bulk access page
x fix that nav is no longer showing which page is selected
x change where “overview” button takes you to top of page
- lorem ipsum in gallery page
x add h2o to gallery page

**Comment by anastasia** [comment]
- sharing buttons in pages including:
  - footer
  - gallery pages (share a limerick!)

**Comment by anastasia** [comment]
- api.html doesn't have a working navigation (js file missing)
- arrows not showing up on certain devices
- add shadow or outline behind nav on small screens, so that you can tell where nav ends and content begins
- fix styling in bulk access

**Comment by bensteinberg** [comment]
* lorem in /about/#data

**Comment by anastasia** [comment]
>     * lorem in /about/#data

@ChefAndy's on it!

**Comment by jcushman** [comment]
![image](https://user-images.githubusercontent.com/376272/45451858-59145380-b6aa-11e8-9157-bf35b60ca227.png)

**Comment by jcushman** [comment]
Let's call this done 🚀
