### ISSUE TITLE
Extract parallel citations from text

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#393]
Find parallel cites like `100 Mass. 100, 200 N.E.2d 200` in case text and use to add citation metadata.

**Comment by mlissner** [comment]
I took a stab at this a while back. It was fun, but I never quite finished it. I've still got the code, but the general idea was to identify citations that occurred next to each other, and whenever I did, add that co-occurence as two nodes in a graph with a edge between them. Go through the entire corpus adding nodes and edges, and whenever you find another co-occurrence, increment the edge weight by one. Once done, you've got a nice wieghted network graph of co-occurrences. Cool!

I pretty much got that part done and can share it if you want. The next step I envisioned was to figure out what weight of co-occurrence was good enough to actually trust and add to the database. I never got that part done. It seemed fairly dangerous, and I didn't have a good way to really poke at the graph to find oddities and outliers.

**Comment by ChefAndy** [comment]
I know we did a big push on citation work. @jcushman do you think this issue is still relevant, or should we make a separate one?

**Comment by jcushman** [comment]
This is still relevant, but would now be easier with the new eyecite library. Doing it properly might start by teaching eyecite to emit parallel citations in some structured way, since it's a little messy the way it is now. Happy to talk more with anyone who wants to work on it.

**Comment by kilbergr** [comment]
Parallel cites are the same case being in two different reporters. 
Cool thing for someone else to do?
