### ISSUE TITLE
Change bulk downloads to use API format

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#397]
For our bulk downloads we should format the files the same way the API does. Offer two versions: text and HTML.

**Comment by john-bowers** [comment]
- Render "jurisdiction," "court," "reporter" as ids, providing a lookup table alongside the data dump
- Drop "url" field
- Remove pagination fields (if necessary)
- Remove human-readable tabbing

**Comment by jcushman** [comment]
Done
