### ISSUE TITLE
500 error getting casebody for this case

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#406]
https://capapi.org/api/v1/cases/1320368/?full_case=true&body_format=html

**Comment by ChefAndy** [comment]
It only seems to error out if body_format is set to html, but setting it to other (unrecognized) formats just provides an empty 200 response.

Oddly enough, the request works just fine in curl.

**Comment by ChefAndy** [comment]
Case_ID: 32044078574332_0023

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/share/capstone/capstone/scripts/generate_case_html.py", line 108, in generate_html
    element.attrib['href'] = "#headnote_" + bracketnum_number.search(element_text_copy).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ChefAndy** [comment]
Will confirm when deployed.

**Comment by bensteinberg** [comment]
Will deploy when I finish running some updates on the server....

**Comment by bensteinberg** [comment]
Deployed

**Comment by jcushman** [comment]
Confirmed
