### ISSUE TITLE
case can't be found

### ISSUE THREAD

**Issue by jessfarrell** [harvard-lil/capstone#436]
Pulled from this citation and searched by decision date, case number 003290 and also case number 1994CR003290: State of Colorado v Clark (Sean O'Neill) No 1994CR003290 (Colo Dist Ct 16 February 1996)

**Comment by jessfarrell** [comment]
Citation may have some incorrect info but confirmed decision date from another source. Case title may alternately be cited as People v. Clark (Sean O'Neill)

**Comment by jcushman** [comment]
Hi, Jess! Thanks for checking out the API. Can you include some links to what search you tried and what you expected to find there?

(Is this a published case? Note that we only have cases included in a court's official reports -- we should really have a readable list somewhere of which specific books that is ...)

**Comment by jessfarrell** [comment]
I am definitely a little confused about if I should even expect to find it in CAP or not. I realized that the citation was actually a docket which I’m guessing is far out of scope? I don’t understand what a docket is ☺ I think a summary of a case, and something that would not fit into recorded case law?

Jess

**Comment by jcushman** [comment]
Ah, yep, definitely out of scope. :) The docket is the list, kept by the court clerk, of documents filed in a case in that court, along with some metadata like the parties and attorneys and current status of the case.

Here's the docket search page for Colorado, for example: https://www.courts.state.co.us/dockets/index.cfm

I did a search for 1994 CR 003290, but I suspect their database doesn't go back that far.
