### ISSUE TITLE
AJAX update filters based on selections

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#453]
For example, if you select a jurisdiction, the user could be presented with a list of courts within that jurisdiction.

**Comment by ChefAndy** [comment]
This would still be a nice-to-have feature in the browsable API as well as SPAs like search and chronolawgic. At the outset it seems like a good match for a JS library we could include in multiple interfaces but that might be too challenging to include in the browsable API? Does that matter?

**Comment by kilbergr** [comment]
Not doing.
