### ISSUE TITLE
aria-current

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/capstone#474]
It's common to change the color/appearance of an item in a `nav` when the link leads to the current page. CAP does this by making the top-level of the navigation appear in an orange font. 

There is an equivalent for screenreaders: `aria-current`: https://tink.uk/using-the-aria-current-attribute/. 

The easiest thing to do is to attach your visual styles in css to the `aria-current` attribute selector, so you don't have to make multiple changes in your html, say, both applying a class "current" and then having to remember to do `aria-current` as well. For example:
```
li[aria-current="page"] {
   color: orange
}
```

We should try to add this to the CAP main navigation.

But, it's a little complicated, which is why I'm not just sending a PR right now, instead of writing this up. Usually, you only use `aria-current="page"` once on a given page. But, the CAP main navigation has a complex structure: some of the dropdowns represent single pages, with sub-items pointing to in-page anchros, and some of the dropdowns represent conceptual "sections" of the site, with sub-items pointing to different pages. 

I'm not sure, even conceptually, the best way to apply `aria-current` here so as to avoid confusion, rather than add confusion LOL!

Let's skip it for now, and readdress pending more thinking, both about aria and about this navigation's UX in general.

**Comment by ChefAndy** [comment]
Right now, this is what our currently selected nav item looks like:

`<a class="nav-link dropdown-toggle selected" href="#" id="navbar-dropdown-tools" role="button" aria-haspopup="true" aria-expanded="true" data-toggle="dropdown" style="display: block;">Caselaw</a>`

But that's only at the top level of the dropdown... whatever is selected in the rest of the dropdown is no different. For example, _search_ is under _caselaw_ but when you go to the search page, the _search_ entry in the dropdown has the same appearance when the menu is exapnded. _caselaw_ however is yellow.

Should we be using aria-current for either of these options?
