### ISSUE TITLE
Section signs in headings are read

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/capstone#478]
Consider adding the sqiggly that precedes certain headings as a background image to prevent them being read by screen readers:

![image](https://user-images.githubusercontent.com/11020492/45770156-9aa78000-bc0f-11e8-9359-c6edf1c19588.png)

There are other techniques too, if that one isn't convenient.

**Comment by bensteinberg** [comment]
https://en.wikipedia.org/wiki/Section_sign

**Comment by anastasia** [comment]
<img width="401" alt="screen shot 2018-09-19 at 4 05 16 pm" src="https://user-images.githubusercontent.com/1494102/45778165-de0ce900-bc25-11e8-9a03-7a58bd7b1aae.png">
an annoying attempt at being cute

**Comment by rebeccacremona** [comment]
It IS cute. This might actually not be that annoying, esp. if it says "section" and the user gets the cuteness. It would be interesting to find out what one of the people who use screenreaders at HLS thinks.

**Comment by ChefAndy** [comment]
This was all revamped— I don't think we're using the section symbol in nav.
