### ISSUE TITLE
Colors are tough to distinguish

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/capstone#510]
Simulation suggests these are unfortunately more-or-less indistinguishable for people with any variety of color blindness. (Try the nocoffee vision simulation chrome extension to reproduce)

The distinction is also less obvious at small screen sizes and for folks w/low vision.

blue/purple links (hover, visited)
![image](https://user-images.githubusercontent.com/11020492/45905442-5b6b6180-bdbe-11e8-84b8-950b7a4aaec2.png)

yellow/orange (current vs selected)
![image](https://user-images.githubusercontent.com/11020492/45905339-07607d00-bdbe-11e8-88de-5f354a9bd849.png)

**Comment by rebeccacremona** [comment]
Everything else that disproportionately affects people with color blindness seems to have been covered in https://github.com/harvard-lil/capstone/issues/505. Huzzah for automated testing.

**Comment by ChefAndy** [comment]
Addressed in #505
