### ISSUE TITLE
List style for list of links in text

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#517]
It could be nice to have a special list style for lists like this:

![image](https://user-images.githubusercontent.com/376272/46028756-6a545b80-c0bf-11e8-865a-72c94d472c80.png)

And

![image](https://user-images.githubusercontent.com/376272/46028761-6c1e1f00-c0bf-11e8-87b7-f5f49d0e28d9.png)

Maybe some sort of rightward arrow for each one as a nudge to click?

**Comment by ChefAndy** [comment]
These old UI tickets probably can be closed because they need to be part of a larger UX review.
