### ISSUE TITLE
invalid filter choice doesn't give value that you entered

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#520]
{
    "jurisdiction": [
        "Select a valid choice. %(value)s is not one of the available choices."
    ]
}

**Comment by mlissner** [comment]
Just ran into this error message and it seemed to be OK? Here's what I saw at https://api.case.law/v1/cases/12110892/?full_case=True : 

     "Select a valid choice. True is not one of the available choices."

What I came to report though is that it doesn't tell you what the valid choices actually are. In this case it was `true`, not `True`.

**Comment by ChefAndy** [comment]
Not reproducible ATM
