### ISSUE TITLE
Groovier 404 pages

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#543]
Current:

![screenshot_2018-10-03 404 not found caselaw access project](https://user-images.githubusercontent.com/2140548/46415311-02bb9300-c6f3-11e8-984a-3b16ef0856da.png)

**Comment by jcushman** [comment]
Currently looking like this:

![image](https://user-images.githubusercontent.com/376272/46828811-10fc5580-cd6a-11e8-91c9-d4b3a827fdc4.png)
