### ISSUE TITLE
styling on contact-us success page

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#545]
https://case.law/contact/

![image](https://user-images.githubusercontent.com/376272/46427411-60f66f00-c70f-11e8-8980-8815f5d5322f.png)

**Comment by anastasia** [comment]
Actually this has to be reopened — working on it now! Currently looks like this:

<img width="1440" alt="screen shot 2018-10-11 at 3 29 16 pm" src="https://user-images.githubusercontent.com/1494102/46828982-7a7c6400-cd6a-11e8-8fc6-f9241eee5d4d.png">
