### ISSUE TITLE
Make CAP sharing friendly

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#581]
Includes #330

This is what facebook sharing looks like right now:
<img width="527" alt="screen shot 2018-10-11 at 2 45 12 pm" src="https://user-images.githubusercontent.com/1494102/46826569-51f16b80-cd64-11e8-8240-09af655b7ff3.png">

twitter sharing preview is nonexistent. Would be cool if we could make CAP a sharing-friendly website for social media like twitter, facebook, slack.

**Comment by jcushman** [comment]
These are looking good!
