### ISSUE TITLE
Glossary entry

### ISSUE THREAD

**Issue by JohnHostage** [harvard-lil/capstone#588]
The entry for Jurisdiction in the glossary is missing info after the "or" and the second sentence is incomplete.

**Comment by jcushman** [comment]
Hi, John! Is this your first time on Github? If so, congratulations, and thanks for the catch! A fix for this should show up the next time we deploy.

**Comment by JohnHostage** [comment]
Hi Jack,

Yes, it was my first time on Github. ☺

John

------------------------------------------
John Hostage
Senior Continuing Resources Cataloger
Harvard Library--Information and Technical Services
Langdell Hall 194
Harvard Law School Library
Cambridge, MA 02138
hostage@law.harvard.edu<mailto:hostage@law.harvard.edu>
+(1)(617) 495-3974 (voice)
+(1)(617) 496-4409 (fax)
ISNI 0000 0000 4028 0917
