### ISSUE TITLE
Left Nav Overflow - Multiple Browsers

### ISSUE THREAD

**Issue by lkfitz** [harvard-lil/capstone#616]
Just wrapped up first round of testing in SauceLabs with the following specs:

case.law
Firefox 62
Windows 10
1024 x 768

In the following areas of the website, we're seeing overflow of left nav text:
case.law/about/
case.law/api
case.law/bulk

Screenshots attached. 

![about](https://user-images.githubusercontent.com/11711958/47041607-42549700-d157-11e8-9810-44320e48374e.png)
![api](https://user-images.githubusercontent.com/11711958/47041608-42ed2d80-d157-11e8-9cbf-493dd6f7394b.png)
![bulk](https://user-images.githubusercontent.com/11711958/47041609-42ed2d80-d157-11e8-91fd-d0ecfefc50dd.png)

**Comment by lkfitz** [comment]
Running into similar obstacles in the left navigation shown across other browsers:
case.law
Microsoft Edge 17
Windows 10
1024 x 768

Active in following areas of case.law (screenshots below):
case.law/privacy
case.law/api 
case.law/bulk 
case.law/about

![privacy](https://user-images.githubusercontent.com/11711958/47093359-04a74b00-d1f7-11e8-8672-5821f724ccf4.png)
![api](https://user-images.githubusercontent.com/11711958/47093360-053fe180-d1f7-11e8-90fe-701217947344.png)
![bulk](https://user-images.githubusercontent.com/11711958/47093361-053fe180-d1f7-11e8-8ccf-629bc81efb2e.png)
![about](https://user-images.githubusercontent.com/11711958/47093362-053fe180-d1f7-11e8-9b24-9a7c71c14ec4.png)

**Comment by lkfitz** [comment]
Running into this same bug in IE testing with the following specs:

case.law
Internet Explorer 11
Windows 10
1024 x 768

Bug active in following spaces:
case.law/privacy
case.law/about 
case.law/api 
case.law/bulk
![about](https://user-images.githubusercontent.com/11711958/47386975-0e8beb00-d6dc-11e8-9e5d-1bbc184fc644.png)
![api](https://user-images.githubusercontent.com/11711958/47386976-0e8beb00-d6dc-11e8-9bd0-0ed5750c8f84.png)
![bulk](https://user-images.githubusercontent.com/11711958/47386977-0e8beb00-d6dc-11e8-8f30-0969882cc623.png)
![privacy](https://user-images.githubusercontent.com/11711958/47386979-0e8beb00-d6dc-11e8-8267-eac6453668e7.png)

**Comment by ChefAndy** [comment]
Nobody visits with IE anymore.
