### ISSUE TITLE
Some Montana cases have wrong (U.S.) jurisdiction

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#623]
This case is coded as US jurisdiction when it should be Montana:

https://api.case.law/v1/cases/3749432/?full_case=true&format=xml
https://searchcourts.mt.gov/APP/connector/1/221/url/321Z18S_01YEHVWPM005HTJ.pdf

There are about 50 other Montana Supreme Court cases with US jurisdiction -- probably those all want to be Montana jurisdiction?

**Comment by jcushman** [comment]
(Most likely an issue with volume 32044132260746 ?)

**Comment by jcushman** [comment]
I did a general scan and found lots of other courts with a similar situation, where they have just a few cases with an improbable jurisdiction. Those cases are collected in the "Courts with multiple jurisdictions" spreadsheet on the Google Drive, and ready for review.

**Comment by anastasia** [comment]
Maybe helpful? Maybe not?

Here's a chart of the U.S. (minus territories) courts charted out using gmaps (matching on the jurisdiction we have for each). Maybe this could be useful for quickly uncovering problematic areas.

<img width="603" alt="screen shot 2018-11-08 at 1 21 55 pm" src="https://user-images.githubusercontent.com/1494102/48219963-ff53a100-e35b-11e8-94e7-87a9e5110cdd.png">

Go here for interaction: https://plot.ly/create/?fid=mowdydod:2#/

**Comment by jcushman** [comment]
Original case was fixed by our court cleanup pass.
