### ISSUE TITLE
Scroll Jumbles Top Nav (Internet Explorer)

### ISSUE THREAD

**Issue by lkfitz** [harvard-lil/capstone#627]
Testing in IE using the following specs, scrolling down jumbles the top navigation (shown in screenshare below).

case.law
Internet Explorer 11
Windows 10
1024 x 768
![xkvedl9gwr](https://user-images.githubusercontent.com/11711958/47387438-5d865000-d6dd-11e8-8d59-ed0b50eb0e6e.gif)

**Comment by ChefAndy** [comment]
Nobody visits with IE anymore.
