### ISSUE TITLE
Minimized U.S. Map (Internet Explorer)

### ISSUE THREAD

**Issue by lkfitz** [harvard-lil/capstone#628]
Testing with the following IE specs, the U.S. map visualization is minimized.
case.law
Internet Explorer 11
Windows 10
1024 x 768
![infographic](https://user-images.githubusercontent.com/11711958/47387634-f026ef00-d6dd-11e8-96be-ffc45731e76d.png)

**Comment by ChefAndy** [comment]
Nobody visits with IE anymore.
