### ISSUE TITLE
Add a box on the homepage to ask why people are interested in caselaw

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#676]
Just tossing this in for discussion -- I know other projects have benefited from collecting stories about why people are interested in their stuff.

**Comment by jcushman** [comment]
... analogous to the “Share Your Story” feature DASH has -- talk to @rebeccacremona for details!

**Comment by ChefAndy** [comment]
I think things like this should be part of a larger UX review if we decide to implement them. I'm closing this, but will include mechanisms for getting this sort of feedback in a larger UX improvement issue or project.
