### ISSUE TITLE
User account page shouldn't be cached by browser

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#679]
Ben reports that he had to hit refresh to see an update.

**Comment by bensteinberg** [comment]
Though note that Ben may not be the most reliable narrator.

**Comment by jcushman** [comment]
Saw this again over Ben's shoulder -- after submitting research access request and clicking "back to account", user account page doesn't show that request was submitted until hitting refresh. Page must have wrong cache header?
