### ISSUE TITLE
Preloaded HSTS for case.law

### ISSUE THREAD

**Issue by lgarron** [harvard-lil/capstone#695]
I'm glad to see case.law uses HTTPS! :-D

Since it's a very memorable URL, I think it would be great to give it full protection by adding an HSTS header and preloading the domain: https://hstspreload.org/?domain=case.law

**Comment by ChefAndy** [comment]
Thoughts @bensteinberg?

**Comment by bensteinberg** [comment]
Hm, we have HSTS already; I'm reading up on preloading.

**Comment by bensteinberg** [comment]
Returning to this much later: it sounds like preloading is overkill, and can be risky -- I don't think we're really at risk of accidentally locking out a non-HTTPS subdomain, but I'm closing this and leaving our HSTS settings as they are.

**Comment by lgarron** [comment]
> Returning to this much later: it sounds like preloading is overkill, and can be risky -- I don't think we're really at risk of accidentally locking out a non-HTTPS subdomain, but I'm closing this and leaving our HSTS settings as they are.

Given the state of web security in 2022, I find this a disappointing conclusion. 😕
This is a fairly straightforward configuration to protect the site, andiIt sounds from your comment that risk of breakage is low. The site is already using HTTPS almost all the time, and yet it's unprotected against malicious or commercial interference when actually needed, particular when `case.law` is typed into the URL bar by hand.
