### ISSUE TITLE
User-Reported: API Req's fail w/o user-agent string

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#698]
"While putting together code to compile case data for securities litigation, I notice that your servers require an explicit User-Agent header (even if it's empty). I had no problem with curl but Python (urllib/urllib2) returned a 403 unless the User-Agent header was defined."

Not tested/confirmed. Likely a docs issue.

**Comment by jcushman** [comment]
Fixed -- this was a Cloudflare setting.

**Comment by jcushman** [comment]
![image](https://user-images.githubusercontent.com/376272/49298693-074ebe80-f48c-11e8-9acc-45aed639f0b1.png)
![image](https://user-images.githubusercontent.com/376272/49298698-09b11880-f48c-11e8-82a9-f6d7924e419f.png)
