### ISSUE TITLE
Disable django template's html autoescape for email template

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/capstone#701]
To avoid `Caselaw related to an institution&#39;s director promising the status of directorship for the price of a Zingerman&#39;s sandwich and not following through` and similar.

**Comment by rebeccacremona** [comment]
Update: don't follow this example in these links.
Original mesage:

~Perma does this like:
https://github.com/harvard-lil/perma/blob/8f922db305c6d50e7700592088d3e975282cc8da/perma_web/perma/settings/deployments/settings_common.py#L128~

~and then~

~https://github.com/harvard-lil/perma/blob/759a886cd7ce65ddf30019456cd92387a5414125/perma_web/perma/email.py#L58~

**Comment by rebeccacremona** [comment]
Update: don't follow the example in those links.

**Comment by rebeccacremona** [comment]
Django's error-handling code, which also sends plaintext emails, uses this approach: https://github.com/django/django/blob/master/django/views/debug.py#L340. But don't trust me on the topic 😜

**Comment by ChefAndy** [comment]
This doesn't seem to be the case anymore? At the very least, the modified email that came through my local log isn't interpreted with encoded HTML entities, and that includes the headers, etc. so I can't imagine it goes through any sort of encoding after that...

```Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Subject: Caselaw Access Project: Verify your email address
From: info@example.com
To: test@example.com
Date: Tue, 14 Sep 2021 18:55:40 -0000
Message-ID: <xyz123>

Please click here to ver'<>&ify your email address:

https://case.test:8000/user/verify-user/3/xyz123/

If you received this message in error, please ignore it.
-------------------------------------------------------------------------------```
