### ISSUE TITLE
head_matter missing from XML format

### ISSUE THREAD

**Issue by jhayden1** [harvard-lil/capstone#708]
Hi folks, I noticed that the head-matter is missing from the XML format , but is present in the plain text format. Can you pop it in there for the XML format too?
Thanks
/jh

[missing_head_matter.zip](https://github.com/harvard-lil/capstone/files/2574464/missing_head_matter.zip)

**Comment by ChefAndy** [comment]
While it's is not labelled head matter in the XML, the data is there. The individual head matter fields, such as parties, attorneys, etc. are labelled as such rather than being clumped together as head matter.
