### ISSUE TITLE
Case Count metadata displaying NULL

### ISSUE THREAD

**Issue by ErinEMcC** [harvard-lil/capstone#711]
Periodically, I'm running into nulls for case counts when I run a search in the browser API. It might be related to quantity of results. EG: text searching for "Regulation" =
2014 (1,843 cases)
2014 - 2015 (3,675 cases)
2014-2016 (NULL)

**Comment by jcushman** [comment]
Hi, Erin! This is (briefly) documented in our API docs:

"Responses also include a "count" key. Occasionally this may show "count": null, indicating that the total count for a particular query has not yet been calculated."

https://case.law/api/#pagination

Basically the API allows for 2 seconds to calculate a count, and if that takes too long (which is especially likely for full text searches) it returns null. Behind the scenes, we'll spend another couple of minutes generating a count, so you may see it on subsequent result pages, although our frontend cache means you won't see it again by repeating precisely the same request.
