### ISSUE TITLE
Glacier/delete originals for CAPTARed volumes

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#717]

**Comment by bensteinberg** [comment]
There are two ways to get things into Glacier. One is uploading them directly, and then they get new random names and you have to keep track of them. The other is by Lifecycle Rule from an S3 bucket, which is what we are going to use. Lifecycle rules can apply after an object is a given age or on a given date; they can apply to all items in a bucket or selectively, by object prefix or tag. 

One approach here is to create a lifecycle rule on the buckets in question to move objects with a given tag to Glacier immediately, then tag all objects in volumes for which there's a validated captar. 

Another approach is that of https://stackoverflow.com/a/31730123 (a little dated but ok): move volumes with validated captars from their original buckets to a bucket with a glacier-all-immediately lifecycle rule.

(Restoring from Glacier in this situation can be done per-object with `s3cmd`, e.g. something like

      cat unglacier.txt | parallel s3cmd restore --restore-days=60 --recursive s3://bckt/fldr/{}/

where `unglacier.txt` has your second-level folder names i.e. volumes.)
