### ISSUE TITLE
Counts taking too long

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#725]
We're not getting a count for http://api.case.law/v1/cases/ . On datamod, the count query takes 10 minutes to return, which is long enough for the background task that does counts to time out:

```
capdb=> SELECT COUNT(*) AS "__count" FROM "capdb_casemetadata" WHERE ("capdb_casemetadata"."court_id" IS NOT NULL AND "capdb_casemetadata"."duplicative" = false AND "capdb_casemetadata"."jurisdiction_id" IS NOT NULL);
 __count
---------
 6606269
(1 row)

Time: 572878.383 ms
```

Is the time similar on the api server? If so, can that be optimized?

**Comment by bensteinberg** [comment]
On the timeout end of this problem, this is weird: I see `ERROR:  canceling statement due to statement timeout` in the logs, but we're not setting `statement_timeout` to anything but the default:
```
#statement_timeout = 0			# in milliseconds, 0 is disabled
```

**Comment by bensteinberg** [comment]
I wonder if this is being set by the client....

**Comment by bensteinberg** [comment]
ah yep, in settings_base.py:
```
TASK_COUNT_TIME_LIMIT = 120
```
So why is this query taking more than two minutes?

**Comment by bensteinberg** [comment]
The query in the log, `SELECT COUNT(*) AS "__count" FROM "capdb_casemetadata" WHERE ("capdb_casemetadata"."court_id" IS NOT NULL AND "capdb_casemetadata"."duplicative" = false AND "capdb_casemetadata"."jurisdiction_id" IS NOT NULL)`, takes 2-3 seconds in the dbshell.

**Comment by bensteinberg** [comment]
Troubleshooting 101: the celery worker wasn't running.

> You do that, you go to the box, you know. Two minutes, by yourself, you know and you feel shame, you know.
