### ISSUE TITLE
Fix wide.html

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#755]
almost imperceptible but still very annoying line through title 
<img width="340" alt="screen shot 2019-01-11 at 12 23 08 pm" src="https://user-images.githubusercontent.com/1494102/51049397-c0c8a580-159b-11e9-9f43-c9e6b3e2967a.png">
https://case.law/user/login/

**Comment by jcushman** [comment]
@anastasia is this fixed? I can't perceive it. :)

**Comment by anastasia** [comment]
me neither.
