### ISSUE TITLE
overlay of "spinner" doesn't cover full page (on firefox)

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#788]

**Comment by jcushman** [comment]
I'm taking a pass at the spinner. I think it might make sense for it not to block out the page, so you can change the search and re-submit if you have a typo or the search is taking too long.

**Comment by jcushman** [comment]
Spinner is no longer an overlay -- will now be an actual spinner inside the search box, plus the CAP GIF in the results area.
