### ISSUE TITLE
alter scrollToResults to set keyboard focus instead

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#794]
> From the peanut gallery: you might want to consider altering scrollToResults to set keyboard focus instead, at some point. [scrollIntoView)(https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) scrolls the viewport, but leaves keyboard focus unchanged. When you set keyboard focus, the scrolling happens too, automatically.

_Originally posted by @rebeccacremona in https://github.com/harvard-lil/capstone/pull/793#issuecomment-463727109_

**Comment by jcushman** [comment]
Fixed!
