### ISSUE TITLE
Allow devs to load up arbitrary real data

### ISSUE THREAD

**Issue by anastasia** [harvard-lil/capstone#80]
Right now there is a painstaking process involved in loading up case data. 
Instead, in the near future, it might be worth considering adding a script that would do a few things: 
first off, load up the tracking tool data into the dev's local db
secondly, maybe hit up the prod api (using dev's api keys) to download the necessary case xml
thirdly, run ingest_files scripts to make entries for the newly loaded cases

**Comment by jcushman** [comment]
You probably saw this, but note that you can load volumes (currently one volume) in the test_data folder using `fab load_test_data`, including tracking tool data. If you add new volumes there you can grab the prod tracking tool data with `fab write_tracking_tool_fixtures`.

I like the idea of being able to load arbitrary volumes as well from the api ...

**Comment by anastasia** [comment]
Thanks! That makes it loads easier than what I did, I didn't notice the fab task.
Should I close this issue for now or keep it for a blue skies kind of day?
