### ISSUE TITLE
US Reports vol. 131 appendix (lower romans) missing

### ISSUE THREAD

**Issue by ericnystrom** [harvard-lil/capstone#802]
Hello!

In US Reports vol. 131, there is a 280 page appendix that gathers a variety of previously-unreported cases since the beginning of the court.  Here is the appendix: <https://cdn.loc.gov/service/ll/usrep/usrep131/usrep131appendix/usrep131appendix.pdf>

SCDB lists 107 of these cases, and has them cited in a form using small romans for page numbers, like so: 131 U.S. cxiv

These are missing from CAP.

I'd be happy to paste the list of these references from SCDB if that would be helpful.

Thank you!

**Comment by cath9** [comment]
This work is not currently planned, so we are closing the issue.
