### ISSUE TITLE
CAP API auto-rendering URLs in our cases, sort of, badly

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#812]
Noticed while viewing HTML format of the case Jane Doe v. Backpage.com, that our api case view is automatically rendering stuff (like 'Backpage.com' and 'Amazon.com') as hyperlinks, which seems weird.

Example: https://api.case.law/v1/cases/?cite=817+F.3d+12&name_abbreviation=&jurisdiction=&reporter=&decision_date_min=&decision_date_max=&docket_number=&court=&search=&full_case=true&body_format=html

Ben sleuthed to a suggestion that its maybe some default renderer behavior in DRF - https://www.django-rest-framework.org/api-guide/renderers/

Do we (don't we?) want this not to happen?

**Comment by jcushman** [comment]
@ChefAndy, it's too bad to lose clickable links for the root API page ( http://api.case.law/v1/ ). Maybe we should turn off URL rendering with a blacklist instead of a whitelist?

**Comment by ChefAndy** [comment]
Ah, damn. I’ll work on it.
