### ISSUE TITLE
<summary> tags from XML rendered in HTML as <aside> tags

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#813]
Some cases (esp. old SCOTUS cases) have long summaries and headnotes that precede the actual text of the opinions.

In our XML, these are `<summary>` tags or `<headnotes>` tags - e.g. https://api.case.law/v1/cases/1421263/?full_case=true&body_format=xml
In our HTML, these are rendered as `<aside class='summary'>` or `<aside class='headnotes'>` tags - e.g. https://api.case.law/v1/cases/1421263/?full_case=true&body_format=html

Should our HTML be rendering these as `<p>` tags with `class='summary'` or `class='headnotes'` instead?

**Comment by ChefAndy** [comment]
Yeah, that sounds like a much more appropriate tag. I'll get on that.

**Comment by ChefAndy** [comment]
Addressed in #814
