### ISSUE TITLE
HTML: Footnotes in cases with multiple opinions

### ISSUE THREAD

**Issue by ChefAndy** [harvard-lil/capstone#822]

**Comment by ChefAndy** [comment]
Footnotes should have an opinion index in the id of the note to avoid collisions.

**Comment by jcushman** [comment]
Based on further discussion:

Footnotes in each opinion should be 1-indexed by opinion count and footnote count, so first opinion has footnote hashes `footnote_1_1`, `footnote_1_2`, second has `footnote_2_1`, `footnote_2_2`, etc.

We also need a scheme for footnotes outside of opinions -- maybe `footnote_0_1`, `footnote_0_2`?
