### ISSUE TITLE
Get cases and courts by court ID

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#859]
We don't support case queries or court queries by court ID - looks like we only support court short name, which isn't unique

**Comment by anastasia** [comment]
There's a PR out for this right now (#910) but I came here to say that court queries also support slugs, which are unique. Does that match with your experience?

**Comment by jcushman** [comment]
I think this came up because I happened to give Adam a spreadsheet that had court IDs and names, but not slugs, and then it wasn't possible to use anything in the spreadsheet to get back to the unique entry in the API. Slugs would have worked if I had put them in the spreadsheet in the first place.
