### ISSUE TITLE
Missing accessible name

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/capstone#937]
AMP says, "This svg (role=img) does not have a mechanism that allows an accessible name value to be calculated"
```
<svg id="usa-territories-white" 
```
To be investigated.

**Comment by ChefAndy** [comment]
Wave doesn't complain about this, but I gather AMP is a much more useful tool. Should I stick some alt text on there, or something, @rebeccacremona? Would that be problematic when folks try and select individual states using a SR?
