### ISSUE TITLE
Privacy Policy markup

### ISSUE THREAD

**Issue by rebeccacremona** [harvard-lil/capstone#938]
https://github.com/harvard-lil/capstone/blob/6fb66c04a9697bb9a3c76ff0ffd383514651d82e/capstone/capweb/templates/privacy-policy.html#L61

`ol` can only contain `li`, not `p`.

Maybe straight up `h5` and `p` would work, without the wrapping list?

**Comment by jcushman** [comment]
Maybe convert this file to markdown along the way to fixing the markup ...

**Comment by bensteinberg** [comment]
I might try this tomorrow, but if someone else is working on it, let me know.
