### ISSUE TITLE
Homepage tweaks

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#991]
Some followup tweaks to the homepage redesign:

Many hrefs need to be filled in -- they're mostly blank.

Can we add "Browse" to the homepage tools?

![image](https://user-images.githubusercontent.com/376272/58195975-3dc90180-7c97-11e9-8995-68c50413ee03.png)

Gallery should say "see project" and have link to individual project:

![image](https://user-images.githubusercontent.com/376272/58195792-cabf8b00-7c96-11e9-8a85-6b9d9cd3d5bb.png)

Remove "Photo Credit Goes Here":

![image](https://user-images.githubusercontent.com/376272/58195813-d4e18980-7c96-11e9-8566-d7a8f8be435b.png)

Black arrow should be a clickable button, or removed:

![image](https://user-images.githubusercontent.com/376272/58195882-fe021a00-7c96-11e9-9fbf-985136aab8a5.png)

**Comment by ChefAndy** [comment]
I can make that arrow clickable— In the rest of the document those triangle elements are primarily for decoration but it does seem different in this case.

I think I might have missed a commit with those hrefs and photo credits. I'll get that in in a few minutes.
